/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/s777675/.choosenim/toolchains/nim-0.18.0/lib -o '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/datatype.o' '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/datatype.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g;
typedef struct tySequence_8sILwIxsvbEGHvqRfAqOuw tySequence_8sILwIxsvbEGHvqRfAqOuw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ tyTuple_3AUSAsdmFS3CNkloCsXPsQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg;
struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g {
tySequence_8sILwIxsvbEGHvqRfAqOuw* data;
NI counter;
};
struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* data;
tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg data_type;
tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g map;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef tySequence_Zj5xKXgsXnI4n4hPS6nACA* tyArray_CLOk3MRqSsQuFokQJMT41A[2];
struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ {
NI Field0;
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Field1;
tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_8sILwIxsvbEGHvqRfAqOuw {
  TGenericSeq Sup;
  tyTuple_3AUSAsdmFS3CNkloCsXPsQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, NewType_1OrDvBSY7u52nJGIFy71LQ)(void);
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_HTFzlhh8sr9a8r9c9bpxkl50w)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, initTable_SCUEbMWziesIwXeOWYeP7Q)(NI initialSize, tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g* Result);
N_LIB_PRIVATE N_NIMCALL(void, set_xdR1De40IcEo1SBb9chdZbA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, set_K6KwhZ9cv2pvll5CkfvhC7A)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data);
N_LIB_PRIVATE N_NIMCALL(void, set_Xp3F9c7Wyk9aw5wqIMEfqNIA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, setMember_pqS4egFZsR5PxBtO7SQvoQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(void, set_vrU9cS59aU8FM2hT9c9cFsS9aXA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__qvxokL765X9asPj7tHXCHWA)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g* t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* val);
N_LIB_PRIVATE N_NIMCALL(void, setMember_wwrtiLKHc9aDpGpjFAvzAMA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NF data);
N_LIB_PRIVATE N_NIMCALL(void, set_t6CEFOv6znBMha8waSyXsg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data);
N_LIB_PRIVATE N_NIMCALL(void, setMember_PAgGpJCIIqhZA0yig4hbCQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, getMember_yvVQbjF0RhWkiWUEtbAngw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**, X5BX5D__Mh2PDE2aZj7IvVhAjyRVHg)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g* t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, name_jo85WrxxvGczyYBxKKeqlg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, add_U4hPcvFNyC9auE9cmCMKyepA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, concat_ypF9bmw2tUJ9apRGN12wxsGA)(tySequence_Zj5xKXgsXnI4n4hPS6nACA** seqs, NI seqsLen_0);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, subtract_U4hPcvFNyC9auE9cmCMKyepA_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, multiply_U4hPcvFNyC9auE9cmCMKyepA_3)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, divide_U4hPcvFNyC9auE9cmCMKyepA_4)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, str_jo85WrxxvGczyYBxKKeqlg_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, character_bFLW4OOqx9bKx2w1Kij9cmSw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, print_Ocu19cXZ6V6m4mwkPZarmCg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, write_WXXQ9aVQjO9b6UKpx9c5niwxw)(FILE* f, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, input_0ib9acUht4wiK9a8GHD8JyOQ)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, rawGet_hjYwPIBjNX9czk6X7LezFngtables)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_XGrVhF2dax5svZ9a35kK6KQ)(NF* x, NI xLen_0);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__LB49bmI9btAcaHBpfQPNZnlQ)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* x, tySequence_Zj5xKXgsXnI4n4hPS6nACA* y);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_hh1W4yWFglgHR3LSK9bOieQ)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_3CA9cb9cSyAIauLFzaL5Xuww)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g* t, tySequence_8sILwIxsvbEGHvqRfAqOuw** data, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_mQfXJ4tCsxv3iqALNAZikAtables)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__G3VCj0QLP6L9ciHFo1UaKMQ)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString_4GrnMC9cMElSx0QoiZQ6BgA)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_uYpHostkmAgm4RjFRNh9cFA)(NimStringDesc** s, NF x);
TNimType NTI_mf33P9ac6h0JtdyXNBo6iKQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
TNimType NTI_WCChZCx9aK9bdnLmmheMmbJg_;
extern TNimType NTI_WAyqrCgQAr5q2ts4Hy4n6g_;
TNimType NTI_HTFzlhh8sr9a8r9c9bpxkl50w_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_V8Z7lVl09aQauzyhNRu9b3GQ_7, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TM_V8Z7lVl09aQauzyhNRu9b3GQ_8, "", 0);
STRING_LITERAL(TM_V8Z7lVl09aQauzyhNRu9b3GQ_10, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_V8Z7lVl09aQauzyhNRu9b3GQ_11, "this.data_type == data.data_type ", 33);
STRING_LITERAL(TM_V8Z7lVl09aQauzyhNRu9b3GQ_14, " ", 1);
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tyRef_HTFzlhh8sr9a8r9c9bpxkl50w)(void* p, NI op) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* a;
	a = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)p;
	nimGCvisit((void*)(*a).data, op);
	nimGCvisit((void*)(*a).map.data, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, NewType_1OrDvBSY7u52nJGIFy71LQ)(void) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("NewType", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(13, "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*) newObj((&NTI_HTFzlhh8sr9a8r9c9bpxkl50w_), sizeof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ));
	nimln_(14, "datatype.nim");
	if ((*result).data) { nimGCunrefNoCycle((*result).data); (*result).data = NIM_NIL; }
	(*result).data = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeqRC1((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), 0);
	nimln_(15, "datatype.nim");
	(*result).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 3);
	nimln_(318, "tables.nim");
	initTable_SCUEbMWziesIwXeOWYeP7Q(((NI) 64), (&(*result).map));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, set_xdR1De40IcEo1SBb9chdZbA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data) {
	nimfr_("set", "datatype.nim");
	nimln_(19, "datatype.nim");
	if ((*this_0).data) { nimGCunrefNoCycle((*this_0).data); (*this_0).data = NIM_NIL; }
	(*this_0).data = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeqRC1((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), 0);
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(3823, "system.nim");
		i = ((NI) 0);
		nimln_(3824, "system.nim");
		L = (data ? data->Sup.len : 0);
		{
			nimln_(3825, "system.nim");
			while (1) {
				NI T4_;
				NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_6;
				if (!(i < L)) goto LA3;
				nimln_(3826, "system.nim");
				if ((NU)(i) > (NU)(data->Sup.len)) raiseIndexError();
				c = data->data[i];
				nimln_(21, "datatype.nim");
				(*this_0).data = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) incrSeqV2(&((*this_0).data)->Sup, sizeof(NF));
				T4_ = (*this_0).data->Sup.len++;
				(*this_0).data->data[T4_] = ((NF) (((NU8)(c))));
				nimln_(3827, "system.nim");
				TM_V8Z7lVl09aQauzyhNRu9b3GQ_6 = addInt(i, ((NI) 1));
				i = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_6);
				nimln_(3828, "system.nim");
				{
					if (!!(((data ? data->Sup.len : 0) == L))) goto LA7_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_7));
				}
				LA7_: ;
			} LA3: ;
		}
	}
	nimln_(22, "datatype.nim");
	(*this_0).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, set_K6KwhZ9cv2pvll5CkfvhC7A)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data) {
	nimfr_("set", "datatype.nim");
	nimln_(25, "datatype.nim");
	if ((*this_0).data) { nimGCunrefNoCycle((*this_0).data); (*this_0).data = NIM_NIL; }
	(*this_0).data = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeqRC1((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), 1);
	(*this_0).data->data[0] = data;
	nimln_(26, "datatype.nim");
	(*this_0).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, set_Xp3F9c7Wyk9aw5wqIMEfqNIA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("set", "datatype.nim");
	nimln_(29, "datatype.nim");
	genericSeqAssign((&(*this_0).data), (*data).data, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
	nimln_(30, "datatype.nim");
	(*this_0).data_type = (*data).data_type;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_pqS4egFZsR5PxBtO7SQvoQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NimStringDesc* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* instance;
	nimfr_("setMember", "datatype.nim");
	nimln_(35, "datatype.nim");
	instance = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(36, "datatype.nim");
	set_vrU9cS59aU8FM2hT9c9cFsS9aXA(instance, data);
	nimln_(37, "datatype.nim");
	X5BX5Deq__qvxokL765X9asPj7tHXCHWA((&(*this_0).map), name, instance);
	nimln_(38, "datatype.nim");
	(*this_0).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 2);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_wwrtiLKHc9aDpGpjFAvzAMA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NF data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* instance;
	nimfr_("setMember", "datatype.nim");
	nimln_(41, "datatype.nim");
	instance = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(42, "datatype.nim");
	set_t6CEFOv6znBMha8waSyXsg(instance, data);
	nimln_(43, "datatype.nim");
	X5BX5Deq__qvxokL765X9asPj7tHXCHWA((&(*this_0).map), name, instance);
	nimln_(44, "datatype.nim");
	(*this_0).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 2);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_PAgGpJCIIqhZA0yig4hbCQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("setMember", "datatype.nim");
	nimln_(47, "datatype.nim");
	X5BX5Deq__qvxokL765X9asPj7tHXCHWA((&(*this_0).map), name, data);
	nimln_(48, "datatype.nim");
	(*this_0).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 2);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, getMember_yvVQbjF0RhWkiWUEtbAngw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ** T1_;
	nimfr_("getMember", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(50, "datatype.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**)0;
	T1_ = X5BX5D__Mh2PDE2aZj7IvVhAjyRVHg((&(*this_0).map), name);
	result = (*T1_);
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, name_jo85WrxxvGczyYBxKKeqlg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NimStringDesc* result;
	nimfr_("name", "datatype.nim");
	result = (NimStringDesc*)0;
	nimln_(54, "datatype.nim");
	result = copyString(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_8));
	{
		NF c;
		tySequence_Zj5xKXgsXnI4n4hPS6nACA* colontmp_;
		NI i;
		NI L;
		NI T2_;
		c = (NF)0;
		colontmp_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
		nimln_(55, "datatype.nim");
		colontmp_ = (*this_0).data;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NimStringDesc* T5_;
				NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_9;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				c = colontmp_->data[i];
				nimln_(56, "datatype.nim");
				T5_ = (NimStringDesc*)0;
				T5_ = nimFloatToStr(c);
				result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
				nimln_(3809, "system.nim");
				TM_V8Z7lVl09aQauzyhNRu9b3GQ_9 = addInt(i, ((NI) 1));
				i = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_9);
				nimln_(3810, "system.nim");
				{
					NI T8_;
					T8_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T8_ == L))) goto LA9_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_10));
				}
				LA9_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, add_U4hPcvFNyC9auE9cmCMKyepA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("add", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(60, "datatype.nim");
	{
		if (!!(((*this_0).data_type == (*data).data_type))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_11));
	}
	LA3_: ;
	nimln_(61, "datatype.nim");
	result = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(62, "datatype.nim");
	switch ((*this_0).data_type) {
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1):
	{
		nimln_(64, "datatype.nim");
		if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)((*data).data->Sup.len)) raiseIndexError();
		set_t6CEFOv6znBMha8waSyXsg(result, ((NF)((*this_0).data->data[((NI) 0)]) + (NF)((*data).data->data[((NI) 0)])));
	}
	break;
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 0):
	{
		tyArray_CLOk3MRqSsQuFokQJMT41A T7_;
		nimln_(66, "datatype.nim");
		memset((void*)T7_, 0, sizeof(T7_));
		genericSeqAssign((&T7_[0]), (*this_0).data, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
		genericSeqAssign((&T7_[1]), (*data).data, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
		asgnRefNoCycle((void**) (&(*result).data), concat_ypF9bmw2tUJ9apRGN12wxsGA(T7_, 2));
		nimln_(67, "datatype.nim");
		(*result).data_type = ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 0);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, subtract_U4hPcvFNyC9auE9cmCMKyepA_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("subtract", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(71, "datatype.nim");
	{
		if (!!(((*this_0).data_type == (*data).data_type))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_11));
	}
	LA3_: ;
	nimln_(72, "datatype.nim");
	result = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(73, "datatype.nim");
	switch ((*this_0).data_type) {
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1):
	{
		nimln_(75, "datatype.nim");
		if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)((*data).data->Sup.len)) raiseIndexError();
		set_t6CEFOv6znBMha8waSyXsg(result, ((NF)((*this_0).data->data[((NI) 0)]) - (NF)((*data).data->data[((NI) 0)])));
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, multiply_U4hPcvFNyC9auE9cmCMKyepA_3)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("multiply", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(79, "datatype.nim");
	{
		if (!!(((*this_0).data_type == (*data).data_type))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_11));
	}
	LA3_: ;
	nimln_(80, "datatype.nim");
	result = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(81, "datatype.nim");
	switch ((*this_0).data_type) {
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1):
	{
		nimln_(83, "datatype.nim");
		if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)((*data).data->Sup.len)) raiseIndexError();
		set_t6CEFOv6znBMha8waSyXsg(result, ((NF)((*this_0).data->data[((NI) 0)]) * (NF)((*data).data->data[((NI) 0)])));
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, divide_U4hPcvFNyC9auE9cmCMKyepA_4)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("divide", "datatype.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(87, "datatype.nim");
	{
		if (!!(((*this_0).data_type == (*data).data_type))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_11));
	}
	LA3_: ;
	nimln_(88, "datatype.nim");
	result = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(89, "datatype.nim");
	switch ((*this_0).data_type) {
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1):
	{
		nimln_(91, "datatype.nim");
		if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)((*data).data->Sup.len)) raiseIndexError();
		set_t6CEFOv6znBMha8waSyXsg(result, ((NF)((*this_0).data->data[((NI) 0)]) / (NF)((*data).data->data[((NI) 0)])));
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, str_jo85WrxxvGczyYBxKKeqlg_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NimStringDesc* result;
	nimfr_("str", "datatype.nim");
	result = (NimStringDesc*)0;
	nimln_(96, "datatype.nim");
	result = copyString(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_8));
	{
		NF c;
		tySequence_Zj5xKXgsXnI4n4hPS6nACA* colontmp_;
		NI i;
		NI L;
		NI T2_;
		c = (NF)0;
		colontmp_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
		nimln_(97, "datatype.nim");
		colontmp_ = (*this_0).data;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_12;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				c = colontmp_->data[i];
				nimln_(98, "datatype.nim");
				result = addChar(result, ((NIM_CHAR)chckRange(((NI) (c)), 0, 255)));
				nimln_(3809, "system.nim");
				TM_V8Z7lVl09aQauzyhNRu9b3GQ_12 = addInt(i, ((NI) 1));
				i = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_12);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_10));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, character_bFLW4OOqx9bKx2w1Kij9cmSw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NIM_CHAR result;
	nimfr_("character", "datatype.nim");
	result = (NIM_CHAR)0;
	nimln_(100, "datatype.nim");
	if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
	result = ((NIM_CHAR)chckRange(((NI) ((*this_0).data->data[((NI) 0)])), 0, 255));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, print_Ocu19cXZ6V6m4mwkPZarmCg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	nimfr_("print", "datatype.nim");
	nimln_(103, "datatype.nim");
	switch ((*this_0).data_type) {
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 0):
	{
		{
			NF c;
			tySequence_Zj5xKXgsXnI4n4hPS6nACA* colontmp_;
			NI i;
			NI L;
			NI T3_;
			c = (NF)0;
			colontmp_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
			nimln_(105, "datatype.nim");
			colontmp_ = (*this_0).data;
			nimln_(3805, "system.nim");
			i = ((NI) 0);
			nimln_(3806, "system.nim");
			T3_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L = T3_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_13;
					if (!(i < L)) goto LA5;
					nimln_(3808, "system.nim");
					if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
					c = colontmp_->data[i];
					nimln_(106, "datatype.nim");
					write_WXXQ9aVQjO9b6UKpx9c5niwxw(stdout, ((NIM_CHAR)chckRange(((NI) (c)), 0, 255)));
					nimln_(3809, "system.nim");
					TM_V8Z7lVl09aQauzyhNRu9b3GQ_13 = addInt(i, ((NI) 1));
					i = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_13);
					nimln_(3810, "system.nim");
					{
						NI T8_;
						T8_ = (colontmp_ ? colontmp_->Sup.len : 0);
						if (!!((T8_ == L))) goto LA9_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_10));
					}
					LA9_: ;
				} LA5: ;
			}
		}
	}
	break;
	case ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1):
	{
		NimStringDesc* T12_;
		nimln_(109, "datatype.nim");
		if ((NU)(((NI) 0)) >= (NU)((*this_0).data->Sup.len)) raiseIndexError();
		T12_ = (NimStringDesc*)0;
		T12_ = nimFloatToStr((*this_0).data->data[((NI) 0)]);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, T12_);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, input_0ib9acUht4wiK9a8GHD8JyOQ)(void) {
	NimStringDesc* result;
	NimStringDesc* s;
	nimfr_("input", "datatype.nim");
{	result = (NimStringDesc*)0;
	nimln_(113, "datatype.nim");
	s = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	nimln_(114, "datatype.nim");
	if (eqStrings(s, ((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_8))) goto LA1_;
	goto LA2_;
	LA1_: ;
	{
		nimln_(115, "datatype.nim");
		result = copyString(((NimStringDesc*) &TM_V8Z7lVl09aQauzyhNRu9b3GQ_14));
		goto BeforeRet_;
	}
	goto LA3_;
	LA2_: ;
	{
		nimln_(116, "datatype.nim");
		result = copyString(s);
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_15;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_V8Z7lVl09aQauzyhNRu9b3GQ_15 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_15) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_hjYwPIBjNX9czk6X7LezFngtables)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_16;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_XGrVhF2dax5svZ9a35kK6KQ(key->data, key->Sup.len);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqeq__LB49bmI9btAcaHBpfQPNZnlQ(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_V8Z7lVl09aQauzyhNRu9b3GQ_16 = subInt(((NI) -1), h);
	result = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_16);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_mQfXJ4tCsxv3iqALNAZikAtables)(tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_17;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqeq__LB49bmI9btAcaHBpfQPNZnlQ(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_V8Z7lVl09aQauzyhNRu9b3GQ_17 = subInt(((NI) -1), h);
	result = (NI)(TM_V8Z7lVl09aQauzyhNRu9b3GQ_17);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_datatypeInit000)(void) {
	nimfr_("datatype", "datatype.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_datatypeDatInit000)(void) {
static TNimNode* TM_V8Z7lVl09aQauzyhNRu9b3GQ_2[3];
static TNimNode* TM_V8Z7lVl09aQauzyhNRu9b3GQ_3[4];
NI TM_V8Z7lVl09aQauzyhNRu9b3GQ_5;
static char* NIM_CONST TM_V8Z7lVl09aQauzyhNRu9b3GQ_4[4] = {
"String", 
"Float", 
"Class", 
"None"};
static TNimNode TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[9];
NTI_mf33P9ac6h0JtdyXNBo6iKQ_.size = sizeof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ);
NTI_mf33P9ac6h0JtdyXNBo6iKQ_.kind = 18;
NTI_mf33P9ac6h0JtdyXNBo6iKQ_.base = 0;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_2[0] = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[1];
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[1].kind = 1;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[1].offset = offsetof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ, data);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[1].typ = (&NTI_Zj5xKXgsXnI4n4hPS6nACA_);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[1].name = "data";
TM_V8Z7lVl09aQauzyhNRu9b3GQ_2[1] = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[2];
NTI_WCChZCx9aK9bdnLmmheMmbJg_.size = sizeof(tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg);
NTI_WCChZCx9aK9bdnLmmheMmbJg_.kind = 14;
NTI_WCChZCx9aK9bdnLmmheMmbJg_.base = 0;
NTI_WCChZCx9aK9bdnLmmheMmbJg_.flags = 3;
for (TM_V8Z7lVl09aQauzyhNRu9b3GQ_5 = 0; TM_V8Z7lVl09aQauzyhNRu9b3GQ_5 < 4; TM_V8Z7lVl09aQauzyhNRu9b3GQ_5++) {
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5+3].kind = 1;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5+3].offset = TM_V8Z7lVl09aQauzyhNRu9b3GQ_5;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5+3].name = TM_V8Z7lVl09aQauzyhNRu9b3GQ_4[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5];
TM_V8Z7lVl09aQauzyhNRu9b3GQ_3[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5] = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[TM_V8Z7lVl09aQauzyhNRu9b3GQ_5+3];
}
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[7].len = 4; TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[7].kind = 2; TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[7].sons = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_3[0];
NTI_WCChZCx9aK9bdnLmmheMmbJg_.node = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[7];
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[2].kind = 1;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[2].offset = offsetof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ, data_type);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[2].typ = (&NTI_WCChZCx9aK9bdnLmmheMmbJg_);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[2].name = "data_type";
TM_V8Z7lVl09aQauzyhNRu9b3GQ_2[2] = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[8];
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[8].kind = 1;
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[8].offset = offsetof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ, map);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[8].typ = (&NTI_WAyqrCgQAr5q2ts4Hy4n6g_);
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[8].name = "map";
TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[0].len = 3; TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[0].kind = 2; TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[0].sons = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_2[0];
NTI_mf33P9ac6h0JtdyXNBo6iKQ_.node = &TM_V8Z7lVl09aQauzyhNRu9b3GQ_0[0];
NTI_HTFzlhh8sr9a8r9c9bpxkl50w_.size = sizeof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*);
NTI_HTFzlhh8sr9a8r9c9bpxkl50w_.kind = 22;
NTI_HTFzlhh8sr9a8r9c9bpxkl50w_.base = (&NTI_mf33P9ac6h0JtdyXNBo6iKQ_);
NTI_HTFzlhh8sr9a8r9c9bpxkl50w_.marker = Marker_tyRef_HTFzlhh8sr9a8r9c9bpxkl50w;
}

