/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/s777675/.choosenim/toolchains/nim-0.18.0/lib -o '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/output.o' '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/output.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg;
typedef struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct RootObj RootObj;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tySequence_y3L9bP9agLhaHxUzv09cBtsnQ tySequence_y3L9bP9agLhaHxUzv09cBtsnQ;
typedef struct tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg;
typedef struct tySequence_M9amFX5KaZeJ4Y3Xhzlxtew tySequence_M9amFX5KaZeJ4Y3Xhzlxtew;
typedef struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g;
typedef struct tySequence_8sILwIxsvbEGHvqRfAqOuw tySequence_8sILwIxsvbEGHvqRfAqOuw;
typedef struct tyTuple_uUwBhYWaJVX4oTp0wobQJQ tyTuple_uUwBhYWaJVX4oTp0wobQJQ;
typedef struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ tyTuple_3AUSAsdmFS3CNkloCsXPsQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg {
tySequence_M9amFX5KaZeJ4Y3Xhzlxtew* data;
NI counter;
};
struct tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg {
NimStringDesc* program;
tySequence_y3L9bP9agLhaHxUzv09cBtsnQ* data;
tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg registers;
};
typedef NU8 tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg;
struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g {
tySequence_8sILwIxsvbEGHvqRfAqOuw* data;
NI counter;
};
struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* data;
tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg data_type;
tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g map;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyTuple_uUwBhYWaJVX4oTp0wobQJQ {
NI Field0;
NimStringDesc* Field1;
tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* Field2;
};
struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ {
NI Field0;
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Field1;
tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* Field2;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_y3L9bP9agLhaHxUzv09cBtsnQ {
  TGenericSeq Sup;
  tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data[SEQ_DECL_SIZE];
};
struct tySequence_M9amFX5KaZeJ4Y3Xhzlxtew {
  TGenericSeq Sup;
  tyTuple_uUwBhYWaJVX4oTp0wobQJQ data[SEQ_DECL_SIZE];
};
struct tySequence_8sILwIxsvbEGHvqRfAqOuw {
  TGenericSeq Sup;
  tyTuple_3AUSAsdmFS3CNkloCsXPsQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, removeComments_WtmVK9caKwthLMaFyYnRIQw)(NimStringDesc* line, NIM_CHAR sep);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getProgram_BgCRbGagTClHmTNshlrlKg)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_9argyMqCIlB1KDaxUuYVcmw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine_y89bfL07uXzOjT5XgI50WmQ)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc** line);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_z6h4H7z9c0v7FfF4wJw5Pig_5)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_z6h4H7z9c0v7FfF4wJw5Pig_7)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*, NewVirtualMachine_uYt4Wl0wVZx4yQjnla539cA)(NimStringDesc* program);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw seps, NI maxsplit);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, run_Hk03t182DaLk1ms7Ml3iaw_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, set_xdR1De40IcEo1SBb9chdZbA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(void, set_K6KwhZ9cv2pvll5CkfvhC7A)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data);
N_LIB_PRIVATE N_NIMCALL(void, set_Xp3F9c7Wyk9aw5wqIMEfqNIA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, setMember_pqS4egFZsR5PxBtO7SQvoQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(void, setMember_wwrtiLKHc9aDpGpjFAvzAMA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NF data);
N_LIB_PRIVATE N_NIMCALL(void, setMember_PAgGpJCIIqhZA0yig4hbCQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, getMember_yvVQbjF0RhWkiWUEtbAngw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, name_jo85WrxxvGczyYBxKKeqlg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, add_U4hPcvFNyC9auE9cmCMKyepA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, subtract_U4hPcvFNyC9auE9cmCMKyepA_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, multiply_U4hPcvFNyC9auE9cmCMKyepA_3)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, divide_U4hPcvFNyC9auE9cmCMKyepA_4)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, str_jo85WrxxvGczyYBxKKeqlg_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, character_bFLW4OOqx9bKx2w1Kij9cmSw)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, print_Ocu19cXZ6V6m4mwkPZarmCg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_P9cTCUF9bsFLyJycfCP3B2Fg)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, push_iRQeCvHAiTUOQiJiHS9b4rw)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, print_1ZVIadieGRNtczw5SHUtsA)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, input_1ZVIadieGRNtczw5SHUtsA_2)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, store_1ZVIadieGRNtczw5SHUtsA_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, load_1ZVIadieGRNtczw5SHUtsA_4)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, str_1ZVIadieGRNtczw5SHUtsA_5)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, character_1ZVIadieGRNtczw5SHUtsA_6)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, add_1ZVIadieGRNtczw5SHUtsA_7)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, subtract_1ZVIadieGRNtczw5SHUtsA_8)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, multiply_1ZVIadieGRNtczw5SHUtsA_9)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, divide_1ZVIadieGRNtczw5SHUtsA_10)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, setMember_1ZVIadieGRNtczw5SHUtsA_11)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, getMember_1ZVIadieGRNtczw5SHUtsA_12)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, run_1ZVIadieGRNtczw5SHUtsA_16)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, call_1ZVIadieGRNtczw5SHUtsA_13)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, forloop_1ZVIadieGRNtczw5SHUtsA_14)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, whileloop_1ZVIadieGRNtczw5SHUtsA_15)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_parserInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_parserDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_datatypeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_datatypeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_virtualmachineInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_virtualmachineDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, outputDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NimStringDesc* program_5KhcLDqV6p10cOd49bk1bXA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* vm_h9c10yG2Xisz63DjV0B1y6A;
extern TNimType NTI_2lt378e8dPjnODvLPOQ2Rg_;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_z6h4H7z9c0v7FfF4wJw5Pig_2 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_z6h4H7z9c0v7FfF4wJw5Pig_3, "", 0);
STRING_LITERAL(TM_z6h4H7z9c0v7FfF4wJw5Pig_4, "\012", 1);
STRING_LITERAL(TM_z6h4H7z9c0v7FfF4wJw5Pig_6, "<\012-------------------------------+oooooooooooooooo+------------"
"-------------------\\n\012----------------------:///hddddNMMMMMMMMMM"
"MMMMMMNddddh///:----------------------\\n\012--------------------yyd"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyy--------------------\\n\012----"
"------------/+sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs+/----"
"------------\\n\012---------------hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMNh---------------\\n\012------------/yMMMMMMMMMMMMMMMM"
"MMmhhhho----ohhhhmMMMMMMMMMMMMMMMMMMy/------------\\n\012----------/"
"hNMMMMMMMMMMMMMNNd+++:--------------/+++dNNMMMMMMMMMMMMMNh/-----"
"-----\\n\012--------/yMMMMMMMMMMMMMMMy:--------------------------/yM"
"MMMMMMMMMMMMMMy/--------\\n\012-------sNMMMMMMMMMMMMms::------------"
"------------------:/smMMMMMMMMMMMMNs-------\\n\012------smMMMMMMMMMM"
"MMo:------------------------------------:oMMMMMMMMMMMMms------\\n"
"\012-----MMMMMMMMMMMMms------------------yMMMMy------------------sm"
"MMMMMMMMMMMM-----\\n\012---/dMMMMMMMMMMMs:-------------------yMMMMy-"
"------------------/sMMMMMMMMMMMd/---\\n\012---+MMMMMMMMMMMy:--------"
"------------yMMMMy--------------------/yMMMMMMMMMMM+---\\n\012--sNMM"
"MMMMMMMm:----------------------yMMMMy----------------------/mMMM"
"MMMMMMNs--\\n\012--yMMMMMMMMMd+--------------/hhho----yMMMMy--------"
"---------------+dMMMMMMMMMy--\\n\012-+dMMMMMMMMMy---------------+MMM"
"Mmo--yMMMMy------------------------yMMMMMMMMMd+-\\n\012-dMMMMMMMMMs:"
"---------------:+NMMMMd+yMMMMy------------------------/sMMMMMMMM"
"Md-\\n\012-dMMMMMMMMM+-------------------odMMMMMMMMMy---------------"
"----------+MMMMMMMMMd-\\n\012-dMMMMMMMMd/--------------------:+dMMMM"
"MMMy-------------------------/dMMMMMMMMd-\\n\012-dMMMMMMMM----------"
"---------------omMMMMMy---------------------------MMMMMMMMd-\\n\012-"
"dMMMMMMMM---------------------------yMMMMMmo--------------------"
"-----MMMMMMMMd-\\n\012-dMMMMMMMMd/-------------------------yMMMMMMMd"
"+:--------------------/dMMMMMMMMd-\\n\012-dMMMMMMMMM+---------------"
"----------yMMMMMMMMMdo-------------------+MMMMMMMMMd-\\n\012-dMMMMMM"
"MMMs/------------------------yMMMMy+dMMMMN+:---------------/sMMM"
"MMMMMMd-\\n\012-+dMMMMMMMMMy------------------------yMMMMy--omMMMM+-"
"--------------yMMMMMMMMMd+-\\n\012--yMMMMMMMMMd+--------------------"
"---yMMMMy----ohhh/--------------+dMMMMMMMMMy--\\n\012--sNMMMMMMMMMm/"
"----------------------yMMMMy----------------------/mMMMMMMMMMNs-"
"-\\n\012---+MMMMMMMMMMMy/--------------------yMMMMy-----------------"
"---/yMMMMMMMMMMM+---\\n\012---/dMMMMMMMMMMMs/-------------------yMMM"
"My-------------------/sMMMMMMMMMMMd/---\\n\012-----MMMMMMMMMMMMms---"
"---------------yMMMMy------------------smMMMMMMMMMMMM-----\\n\012---"
"---smMMMMMMMMMMMMo:------------------------------------:oMMMMMMM"
"MMMMMms------\\n\012-------sNMMMMMMMMMMMMms//-----------------------"
"-------//smMMMMMMMMMMMMNs-------\\n\012--------:yMMMMMMMMMMMMMMMy/--"
"------------------------/yMMMMMMMMMMMMMMMy:--------\\n\012----------"
":hNMMMMMMMMMMMMMNNd+++/--------------/+++dNNMMMMMMMMMMMMMNh:----"
"------\\n\012------------/yMMMMMMMMMMMMMMMMMMmhhhho----ohhhhmMMMMMMM"
"MMMMMMMMMMMy/------------\\n\012---------------hNMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMNh---------------\\n\012----------------/"
"+sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs+/----------------\\"
"n\012--------------------yydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyy--"
"------------------\\n\012----------------------::::hddddNMMMMMMMMMMM"
"MMMMMNddddh::::----------------------\\n\012------------------------"
"-------+oooooooooooooooo+-------------------------------\\n\012-----"
"----------------------------------------------------------------"
"-----------\\n\012--------------------------------------------------"
"------------------------------\\n\012-------------------------------"
"-------------------------------------------------\\n\012------------"
"-------+o-/oo/-----:/oso+:---:s//s+--:oyyo-----/ooo/------------"
"----\\n\012-------------------mNdhshMo--/hmhsosdNo--oMNho+::Nd+sm/--"
"omdssyNm:--------------\\n\012------------------/Mh:--/Mo-+Ny------d"
"N--dN/----:dNho:--hMhyyyyhMs--------------\\n\012------------------h"
"N:---hN:-yM:-----+Ny-/Ms----//-:+mN::Mh+++++o+:--------------\\n\012"
"-----------------:Ny---:Ny--/mNyooyddo--yN:----dNo+sNy--hNyooymh"
"/---------------\\n\012-----------------/s:---/s:----/oss+:----oo---"
"--:syys/----/oss+:-----------------\\n\012--------------------------"
"------------------------------------------------------\\n> norse "
"=\012\012norse $ | %\012", 4174);
STRING_LITERAL(TM_z6h4H7z9c0v7FfF4wJw5Pig_8, " ", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, removeComments_WtmVK9caKwthLMaFyYnRIQw)(NimStringDesc* line, NIM_CHAR sep) {
	NimStringDesc* result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T1_;
	nimfr_("removeComments", "output.nim");
	result = (NimStringDesc*)0;
	nimln_(11, "output.nim");
	T1_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = nsuSplitChar(line, sep, ((NI) -1));
	if ((NU)(((NI) 0)) >= (NU)(T1_->Sup.len)) raiseIndexError();
	result = nsuStrip(T1_->data[((NI) 0)], NIM_FALSE, NIM_TRUE, TM_z6h4H7z9c0v7FfF4wJw5Pig_2);
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getProgram_BgCRbGagTClHmTNshlrlKg)(NimStringDesc* filename) {
	NimStringDesc* result;
	NimStringDesc* line;
	NimStringDesc* program;
	tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* file;
	nimfr_("getProgram", "output.nim");
	result = (NimStringDesc*)0;
	nimln_(15, "output.nim");
	line = copyString(((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_3));
	nimln_(16, "output.nim");
	program = copyString(((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_3));
	nimln_(17, "output.nim");
	file = newFileStream_9argyMqCIlB1KDaxUuYVcmw(filename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	nimln_(19, "output.nim");
	{
		tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T10_;
		if (!!((file == 0))) goto LA3_;
		{
			nimln_(20, "output.nim");
			while (1) {
				tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T7_;
				NIM_BOOL T8_;
				NimStringDesc* T9_;
				T7_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
				T7_ = &file->Sup;
				T8_ = (NIM_BOOL)0;
				T8_ = readLine_y89bfL07uXzOjT5XgI50WmQ(T7_, (&line));
				if (!T8_) goto LA6;
				nimln_(21, "output.nim");
				line = removeComments_WtmVK9caKwthLMaFyYnRIQw(line, 35);
				nimln_(22, "output.nim");
				T9_ = (NimStringDesc*)0;
				T9_ = rawNewString(line->Sup.len + 1);
appendString(T9_, line);
appendString(T9_, ((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_4));
				program = resizeString(program, T9_->Sup.len + 0);
appendString(program, T9_);
			} LA6: ;
		}
		nimln_(23, "output.nim");
		T10_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
		T10_ = &file->Sup;
		close_4ed7IXme7lqtClFI7s2sTQ_2(T10_);
	}
	LA3_: ;
	nimln_(25, "output.nim");
	result = copyString(program);
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_z6h4H7z9c0v7FfF4wJw5Pig_5)(void) {
	nimGCvisit((void*)program_5KhcLDqV6p10cOd49bk1bXA, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_z6h4H7z9c0v7FfF4wJw5Pig_7)(void) {
	nimGCvisit((void*)vm_h9c10yG2Xisz63DjV0B1y6A, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, set_vrU9cS59aU8FM2hT9c9cFsS9aXA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data) {
	nimfr_("set", "datatype.nim");
	nimln_(18, "datatype.nim");
	set_xdR1De40IcEo1SBb9chdZbA(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, set_t6CEFOv6znBMha8waSyXsg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data) {
	nimfr_("set", "datatype.nim");
	nimln_(24, "datatype.nim");
	set_K6KwhZ9cv2pvll5CkfvhC7A(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, set_2Y1jyXEuyVJJMRJzdwCy8A)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("set", "datatype.nim");
	nimln_(28, "datatype.nim");
	set_Xp3F9c7Wyk9aw5wqIMEfqNIA(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_mmjc6du9cRm3g0zF2PWQmTg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NimStringDesc* data) {
	nimfr_("setMember", "datatype.nim");
	nimln_(34, "datatype.nim");
	setMember_pqS4egFZsR5PxBtO7SQvoQ(this_0, name, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_P2s9bA9clnmQwWyvRBXKKb6Q)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, NF data) {
	nimfr_("setMember", "datatype.nim");
	nimln_(40, "datatype.nim");
	setMember_wwrtiLKHc9aDpGpjFAvzAMA(this_0, name, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_9aMyF1zORtckEpFMAIgfJMA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("setMember", "datatype.nim");
	nimln_(46, "datatype.nim");
	setMember_PAgGpJCIIqhZA0yig4hbCQ(this_0, name, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, getMember_v15KYyP7osL4iouqy0PNvg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("getMember", "datatype.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(50, "datatype.nim");
	result = getMember_yvVQbjF0RhWkiWUEtbAngw(this_0, name);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, name_GjhGrqzaqmtHWEG4AXjCLA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NimStringDesc* result;
	nimfr_("name", "datatype.nim");
{	result = (NimStringDesc*)0;
	nimln_(53, "datatype.nim");
	result = name_jo85WrxxvGczyYBxKKeqlg(this_0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, add_4lYSdUbPLhXZzAgY3UFcLg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("add", "datatype.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(59, "datatype.nim");
	result = add_U4hPcvFNyC9auE9cmCMKyepA(this_0, data);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, subtract_4lYSdUbPLhXZzAgY3UFcLg_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("subtract", "datatype.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(70, "datatype.nim");
	result = subtract_U4hPcvFNyC9auE9cmCMKyepA_2(this_0, data);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, multiply_4lYSdUbPLhXZzAgY3UFcLg_3)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("multiply", "datatype.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(78, "datatype.nim");
	result = multiply_U4hPcvFNyC9auE9cmCMKyepA_3(this_0, data);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, divide_4lYSdUbPLhXZzAgY3UFcLg_4)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("divide", "datatype.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(86, "datatype.nim");
	result = divide_U4hPcvFNyC9auE9cmCMKyepA_4(this_0, data);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, str_GjhGrqzaqmtHWEG4AXjCLA_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NimStringDesc* result;
	nimfr_("str", "datatype.nim");
{	result = (NimStringDesc*)0;
	nimln_(95, "datatype.nim");
	result = str_jo85WrxxvGczyYBxKKeqlg_2(this_0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, character_BWGXL56BUNUogvZ1vpmA8Q)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	NIM_CHAR result;
	nimfr_("character", "datatype.nim");
{	result = (NIM_CHAR)0;
	nimln_(100, "datatype.nim");
	result = character_bFLW4OOqx9bKx2w1Kij9cmSw(this_0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, print_7CDbz9bGshWK9b1JC8Y8cFmQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0) {
	nimfr_("print", "datatype.nim");
	nimln_(102, "datatype.nim");
	print_Ocu19cXZ6V6m4mwkPZarmCg(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_ZSTRa9b146RfJCE4Q5aTd8A)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("pop", "virtualmachine.nim");
{	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(24, "virtualmachine.nim");
	result = pop_P9cTCUF9bsFLyJycfCP3B2Fg(this_0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, push_9bkj57Zw1FsrkVtYamRXsDg)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("push", "virtualmachine.nim");
	nimln_(25, "virtualmachine.nim");
	push_iRQeCvHAiTUOQiJiHS9b4rw(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, print_Hk03t182DaLk1ms7Ml3iaw_9)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("print", "virtualmachine.nim");
	nimln_(29, "virtualmachine.nim");
	print_1ZVIadieGRNtczw5SHUtsA(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, input_Hk03t182DaLk1ms7Ml3iaw_16)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("input", "virtualmachine.nim");
	nimln_(33, "virtualmachine.nim");
	input_1ZVIadieGRNtczw5SHUtsA_2(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, store_Hk03t182DaLk1ms7Ml3iaw_2)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("store", "virtualmachine.nim");
	nimln_(38, "virtualmachine.nim");
	store_1ZVIadieGRNtczw5SHUtsA_3(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, load_Hk03t182DaLk1ms7Ml3iaw)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("load", "virtualmachine.nim");
	nimln_(43, "virtualmachine.nim");
	load_1ZVIadieGRNtczw5SHUtsA_4(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, str_Hk03t182DaLk1ms7Ml3iaw_10)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("str", "virtualmachine.nim");
	nimln_(47, "virtualmachine.nim");
	str_1ZVIadieGRNtczw5SHUtsA_5(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, character_Hk03t182DaLk1ms7Ml3iaw_8)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("character", "virtualmachine.nim");
	nimln_(53, "virtualmachine.nim");
	character_1ZVIadieGRNtczw5SHUtsA_6(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, add_Hk03t182DaLk1ms7Ml3iaw_11)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("add", "virtualmachine.nim");
	nimln_(59, "virtualmachine.nim");
	add_1ZVIadieGRNtczw5SHUtsA_7(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, subtract_Hk03t182DaLk1ms7Ml3iaw_12)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("subtract", "virtualmachine.nim");
	nimln_(64, "virtualmachine.nim");
	subtract_1ZVIadieGRNtczw5SHUtsA_8(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, multiply_Hk03t182DaLk1ms7Ml3iaw_13)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("multiply", "virtualmachine.nim");
	nimln_(69, "virtualmachine.nim");
	multiply_1ZVIadieGRNtczw5SHUtsA_9(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, divide_Hk03t182DaLk1ms7Ml3iaw_14)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("divide", "virtualmachine.nim");
	nimln_(74, "virtualmachine.nim");
	divide_1ZVIadieGRNtczw5SHUtsA_10(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_Hk03t182DaLk1ms7Ml3iaw_6)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("setMember", "virtualmachine.nim");
	nimln_(79, "virtualmachine.nim");
	setMember_1ZVIadieGRNtczw5SHUtsA_11(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getMember_Hk03t182DaLk1ms7Ml3iaw_7)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("getMember", "virtualmachine.nim");
	nimln_(95, "virtualmachine.nim");
	getMember_1ZVIadieGRNtczw5SHUtsA_12(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, run_Hk03t182DaLk1ms7Ml3iaw_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("run", "virtualmachine.nim");
	nimln_(105, "virtualmachine.nim");
	run_1ZVIadieGRNtczw5SHUtsA_16(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, call_Hk03t182DaLk1ms7Ml3iaw_4)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("call", "virtualmachine.nim");
	nimln_(107, "virtualmachine.nim");
	call_1ZVIadieGRNtczw5SHUtsA_13(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, forloop_Hk03t182DaLk1ms7Ml3iaw_15)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("forloop", "virtualmachine.nim");
	nimln_(113, "virtualmachine.nim");
	forloop_1ZVIadieGRNtczw5SHUtsA_14(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, whileloop_Hk03t182DaLk1ms7Ml3iaw_5)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	nimfr_("whileloop", "virtualmachine.nim");
	nimln_(125, "virtualmachine.nim");
	whileloop_1ZVIadieGRNtczw5SHUtsA_15(this_0);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_streamsDatInit000();
	unknown_parserDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	unknown_datatypeDatInit000();
	unknown_virtualmachineDatInit000();
	outputDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_streamsInit000();
	unknown_parserInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	unknown_datatypeInit000();
	unknown_virtualmachineInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T3_;
	NimStringDesc* T4_;
	nimfr_("output", "output.nim");
nimRegisterGlobalMarker(TM_z6h4H7z9c0v7FfF4wJw5Pig_5);
nimRegisterGlobalMarker(TM_z6h4H7z9c0v7FfF4wJw5Pig_7);
	nimln_(28, "output.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = program_5KhcLDqV6p10cOd49bk1bXA; program_5KhcLDqV6p10cOd49bk1bXA = copyStringRC1(((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_6));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(82, "output.nim");
	T2_ = (NimStringDesc*)0;
	T3_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T3_ = nsuSplitCharSet(program_5KhcLDqV6p10cOd49bk1bXA, TM_z6h4H7z9c0v7FfF4wJw5Pig_2, ((NI) -1));
	T4_ = (NimStringDesc*)0;
	T4_ = nsuJoinSep(T3_->data, T3_->Sup.len, ((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_8));
	T2_ = rawNewString(T4_->Sup.len + 2);
appendString(T2_, ((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_8));
appendString(T2_, T4_);
appendString(T2_, ((NimStringDesc*) &TM_z6h4H7z9c0v7FfF4wJw5Pig_8));
	asgnRefNoCycle((void**) (&vm_h9c10yG2Xisz63DjV0B1y6A), NewVirtualMachine_uYt4Wl0wVZx4yQjnla539cA(T2_));
	nimln_(83, "output.nim");
	run_Hk03t182DaLk1ms7Ml3iaw_3(vm_h9c10yG2Xisz63DjV0B1y6A);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, outputDatInit000)(void) {
}

