/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/s777675/.choosenim/toolchains/nim-0.18.0/lib -o '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/parser.o' '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/parser.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_Ga09ahkQ9b222DUS9cyf8kbqg tySequence_Ga09ahkQ9b222DUS9cyf8kbqg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg;
struct tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw {
NimStringDesc* name;
tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg token_type;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Ga09ahkQ9b222DUS9cyf8kbqg {
  TGenericSeq Sup;
  tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*, NewToken_hoNAho3tR9b2M7RY0kFXsOg)(NimStringDesc* name, tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg token_type);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_EGvzJYeQzBOu8VnhDxnsTg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*, Tokenize_ab9c9cD4QZzr08z9anmjNqcGQ)(NimStringDesc* program);
static N_NIMCALL(void, Marker_tySequence_Ga09ahkQ9b222DUS9cyf8kbqg)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
TNimType NTI_q4PLD3QkwJJkBXqGWLsmCw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_d9cU6spIk5Ptk9bUpHLD8kbg_;
TNimType NTI_EGvzJYeQzBOu8VnhDxnsTg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_Ga09ahkQ9b222DUS9cyf8kbqg_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
STRING_LITERAL(TM_jVF9a0kci0U9aAi0LWMoeYpg_6, "\\n", 2);
STRING_LITERAL(TM_jVF9a0kci0U9aAi0LWMoeYpg_7, "\012", 1);
STRING_LITERAL(TM_jVF9a0kci0U9aAi0LWMoeYpg_8, "", 0);
NIM_CONST tyArray_Wfh9bjgBQ4UqJsyISUuDSuA TM_jVF9a0kci0U9aAi0LWMoeYpg_15 = {36,
61,
46,
44,
33,
63,
43,
42,
45,
47,
124,
38,
94,
37,
126,
64}
;
static N_NIMCALL(void, Marker_tyRef_EGvzJYeQzBOu8VnhDxnsTg)(void* p, NI op) {
	tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* a;
	a = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)p;
	nimGCvisit((void*)(*a).name, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*, NewToken_hoNAho3tR9b2M7RY0kFXsOg)(NimStringDesc* name, tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg token_type) {
	tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* result;
	NimStringDesc* T1_;
	nimfr_("NewToken", "parser.nim");
	result = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
	nimln_(11, "parser.nim");
	result = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*) newObj((&NTI_EGvzJYeQzBOu8VnhDxnsTg_), sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw));
	nimln_(12, "parser.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).name; (*result).name = copyStringRC1(name);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(13, "parser.nim");
	(*result).token_type = token_type;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_Ga09ahkQ9b222DUS9cyf8kbqg)(void* p, NI op) {
	tySequence_Ga09ahkQ9b222DUS9cyf8kbqg* a;
	NI T1_;
	a = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NIM_CHAR i;
		NI i_2;
		i = (NIM_CHAR)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_jVF9a0kci0U9aAi0LWMoeYpg_13;
				NI TM_jVF9a0kci0U9aAi0LWMoeYpg_14;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!((NU8)(i) == (NU8)(item))) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_jVF9a0kci0U9aAi0LWMoeYpg_13 = addInt(result, ((NI) 1));
				result = (NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_13);
				nimln_(2188, "system.nim");
				TM_jVF9a0kci0U9aAi0LWMoeYpg_14 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_14);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b3HPX1XboPhUmnxkTjazFQstrutils(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*, Tokenize_ab9c9cD4QZzr08z9anmjNqcGQ)(NimStringDesc* program) {
	tySequence_Ga09ahkQ9b222DUS9cyf8kbqg* result;
	NIM_BOOL isFunction;
	NIM_BOOL isLiteral;
	NimStringDesc* program_2;
	NimStringDesc* tokens;
	NI i;
	NI layer;
	NimStringDesc* current_token;
	NIM_CHAR volatile c;
	NIM_BOOL appendToken;
	nimfr_("Tokenize", "parser.nim");
	result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*)0;
	nimln_(17, "parser.nim");
	result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) newSeq((&NTI_Ga09ahkQ9b222DUS9cyf8kbqg_), 0);
	nimln_(18, "parser.nim");
	isFunction = NIM_FALSE;
	nimln_(19, "parser.nim");
	isLiteral = NIM_FALSE;
	nimln_(20, "parser.nim");
	program_2 = nsuReplaceStr(program, ((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_6), ((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_7));
	nimln_(21, "parser.nim");
	tokens = copyString(program_2);
	nimln_(22, "parser.nim");
	i = ((NI) 0);
	nimln_(24, "parser.nim");
	layer = ((NI) 0);
	nimln_(25, "parser.nim");
	current_token = copyString(((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_8));
	c = (NIM_CHAR)0;
	nimln_(28, "parser.nim");
	appendToken = NIM_TRUE;
	{
		nimln_(30, "parser.nim");
		while (1) {
			TSafePoint TM_jVF9a0kci0U9aAi0LWMoeYpg_9;
			NI TM_jVF9a0kci0U9aAi0LWMoeYpg_16;
			nimln_(31, "parser.nim");
			pushSafePoint(&TM_jVF9a0kci0U9aAi0LWMoeYpg_9);
			TM_jVF9a0kci0U9aAi0LWMoeYpg_9.status = _setjmp(TM_jVF9a0kci0U9aAi0LWMoeYpg_9.context);
			if (TM_jVF9a0kci0U9aAi0LWMoeYpg_9.status == 0) {
				nimln_(32, "parser.nim");
				if ((NU)(i) > (NU)(tokens->Sup.len)) raiseIndexError();
				c = tokens->data[i];
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
				{
					TM_jVF9a0kci0U9aAi0LWMoeYpg_9.status = 0;
					popCurrentException();
					nimln_(34, "parser.nim");
					goto LA1;
					popCurrentException();
				}
			}
			if (TM_jVF9a0kci0U9aAi0LWMoeYpg_9.status != 0) reraiseException();
			nimln_(36, "parser.nim");
			appendToken = NIM_TRUE;
			nimln_(38, "parser.nim");
			{
				NIM_BOOL T8_;
				T8_ = (NIM_BOOL)0;
				T8_ = !(isFunction);
				if (!(T8_)) goto LA9_;
				T8_ = !(isLiteral);
				LA9_: ;
				if (!T8_) goto LA10_;
				nimln_(39, "parser.nim");
				{
					if (!((NU8)(c) == (NU8)(60))) goto LA14_;
					nimln_(40, "parser.nim");
					appendToken = NIM_FALSE;
					nimln_(41, "parser.nim");
					isLiteral = NIM_TRUE;
				}
				goto LA12_;
				LA14_: ;
				{
					nimln_(43, "parser.nim");
					if (!((NU8)(c) == (NU8)(91))) goto LA17_;
					nimln_(44, "parser.nim");
					appendToken = NIM_FALSE;
					nimln_(45, "parser.nim");
					isFunction = NIM_TRUE;
				}
				goto LA12_;
				LA17_: ;
				LA12_: ;
			}
			LA10_: ;
			nimln_(47, "parser.nim");
			{
				if (!isLiteral) goto LA21_;
				nimln_(48, "parser.nim");
				{
					NIM_BOOL T25_;
					NI TM_jVF9a0kci0U9aAi0LWMoeYpg_10;
					tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* T29_;
					NI T30_;
					T25_ = (NIM_BOOL)0;
					T25_ = ((NU8)(c) == (NU8)(62));
					if (!(T25_)) goto LA26_;
					nimln_(398, "system.nim");
					nimln_(48, "parser.nim");
					TM_jVF9a0kci0U9aAi0LWMoeYpg_10 = addInt(i, ((NI) 1));
					if ((NU)((NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_10)) > (NU)(tokens->Sup.len)) raiseIndexError();
					T25_ = !(((NU8)(tokens->data[(NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_10)]) == (NU8)(62)));
					LA26_: ;
					if (!T25_) goto LA27_;
					nimln_(49, "parser.nim");
					appendToken = NIM_FALSE;
					nimln_(50, "parser.nim");
					isLiteral = NIM_FALSE;
					nimln_(51, "parser.nim");
					current_token = copyStr(current_token, ((NI) 1));
					nimln_(52, "parser.nim");
					T29_ = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
					T29_ = NewToken_hoNAho3tR9b2M7RY0kFXsOg(current_token, ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 1));
					result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) incrSeqV2(&(result)->Sup, sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*));
					T30_ = result->Sup.len++;
					asgnRefNoCycle((void**) (&result->data[T30_]), T29_);
					nimln_(53, "parser.nim");
					current_token = copyString(((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_8));
				}
				LA27_: ;
			}
			goto LA19_;
			LA21_: ;
			{
				if (!isFunction) goto LA32_;
				nimln_(56, "parser.nim");
				{
					NI TM_jVF9a0kci0U9aAi0LWMoeYpg_11;
					if (!((NU8)(c) == (NU8)(91))) goto LA36_;
					nimln_(57, "parser.nim");
					TM_jVF9a0kci0U9aAi0LWMoeYpg_11 = addInt(layer, ((NI) 1));
					layer = (NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_11);
				}
				goto LA34_;
				LA36_: ;
				{
					NI TM_jVF9a0kci0U9aAi0LWMoeYpg_12;
					nimln_(58, "parser.nim");
					if (!((NU8)(c) == (NU8)(93))) goto LA39_;
					nimln_(59, "parser.nim");
					TM_jVF9a0kci0U9aAi0LWMoeYpg_12 = subInt(layer, ((NI) 1));
					layer = (NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_12);
					nimln_(60, "parser.nim");
					{
						tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* T45_;
						NI T46_;
						if (!(layer == ((NI) 0))) goto LA43_;
						nimln_(61, "parser.nim");
						appendToken = NIM_FALSE;
						nimln_(62, "parser.nim");
						isFunction = NIM_FALSE;
						nimln_(63, "parser.nim");
						current_token = copyStr(current_token, ((NI) 1));
						nimln_(64, "parser.nim");
						T45_ = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
						T45_ = NewToken_hoNAho3tR9b2M7RY0kFXsOg(current_token, ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 0));
						result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) incrSeqV2(&(result)->Sup, sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*));
						T46_ = result->Sup.len++;
						asgnRefNoCycle((void**) (&result->data[T46_]), T45_);
						nimln_(65, "parser.nim");
						current_token = copyString(((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_8));
					}
					LA43_: ;
				}
				goto LA34_;
				LA39_: ;
				LA34_: ;
			}
			goto LA19_;
			LA32_: ;
			{
				nimln_(68, "parser.nim");
				{
					NIM_BOOL T50_;
					T50_ = (NIM_BOOL)0;
					T50_ = ((NU8)(c) == (NU8)(32));
					if (!(T50_)) goto LA51_;
					T50_ = (((NI) 0) < (current_token ? current_token->Sup.len : 0));
					LA51_: ;
					if (!T50_) goto LA52_;
					nimln_(69, "parser.nim");
					current_token = copyStr(current_token, ((NI) 1));
					nimln_(70, "parser.nim");
					{
						NIM_BOOL T56_;
						tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* T59_;
						NI T60_;
						if ((NU)(((NI) 0)) > (NU)(current_token->Sup.len)) raiseIndexError();
						T56_ = (NIM_BOOL)0;
						T56_ = contains_I9cy9aN2znlBRynMcXN4pBGgstrutils(TM_jVF9a0kci0U9aAi0LWMoeYpg_15, 16, current_token->data[((NI) 0)]);
						if (!T56_) goto LA57_;
						nimln_(71, "parser.nim");
						T59_ = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
						T59_ = NewToken_hoNAho3tR9b2M7RY0kFXsOg(current_token, ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 3));
						result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) incrSeqV2(&(result)->Sup, sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*));
						T60_ = result->Sup.len++;
						asgnRefNoCycle((void**) (&result->data[T60_]), T59_);
					}
					goto LA54_;
					LA57_: ;
					{
						tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* T62_;
						NI T63_;
						nimln_(73, "parser.nim");
						T62_ = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
						T62_ = NewToken_hoNAho3tR9b2M7RY0kFXsOg(current_token, ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 2));
						result = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) incrSeqV2(&(result)->Sup, sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*));
						T63_ = result->Sup.len++;
						asgnRefNoCycle((void**) (&result->data[T63_]), T62_);
					}
					LA54_: ;
					nimln_(74, "parser.nim");
					current_token = copyString(((NimStringDesc*) &TM_jVF9a0kci0U9aAi0LWMoeYpg_8));
				}
				LA52_: ;
			}
			LA19_: ;
			nimln_(76, "parser.nim");
			{
				NimStringDesc* T68_;
				if (!appendToken) goto LA66_;
				nimln_(77, "parser.nim");
				T68_ = (NimStringDesc*)0;
				T68_ = nimCharToStr(c);
				current_token = resizeString(current_token, T68_->Sup.len + 0);
appendString(current_token, T68_);
			}
			LA66_: ;
			nimln_(79, "parser.nim");
			TM_jVF9a0kci0U9aAi0LWMoeYpg_16 = addInt(i, ((NI) 1));
			i = (NI)(TM_jVF9a0kci0U9aAi0LWMoeYpg_16);
		}
	} LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_parserInit000)(void) {
	nimfr_("parser", "parser.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_parserDatInit000)(void) {
static TNimNode* TM_jVF9a0kci0U9aAi0LWMoeYpg_2[2];
static TNimNode* TM_jVF9a0kci0U9aAi0LWMoeYpg_3[4];
NI TM_jVF9a0kci0U9aAi0LWMoeYpg_5;
static char* NIM_CONST TM_jVF9a0kci0U9aAi0LWMoeYpg_4[4] = {
"Function", 
"Literal", 
"Identifier", 
"Operator"};
static TNimNode TM_jVF9a0kci0U9aAi0LWMoeYpg_0[8];
NTI_q4PLD3QkwJJkBXqGWLsmCw_.size = sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw);
NTI_q4PLD3QkwJJkBXqGWLsmCw_.kind = 18;
NTI_q4PLD3QkwJJkBXqGWLsmCw_.base = 0;
NTI_q4PLD3QkwJJkBXqGWLsmCw_.flags = 2;
TM_jVF9a0kci0U9aAi0LWMoeYpg_2[0] = &TM_jVF9a0kci0U9aAi0LWMoeYpg_0[1];
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[1].kind = 1;
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[1].offset = offsetof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw, name);
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[1].name = "name";
TM_jVF9a0kci0U9aAi0LWMoeYpg_2[1] = &TM_jVF9a0kci0U9aAi0LWMoeYpg_0[2];
NTI_d9cU6spIk5Ptk9bUpHLD8kbg_.size = sizeof(tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg);
NTI_d9cU6spIk5Ptk9bUpHLD8kbg_.kind = 14;
NTI_d9cU6spIk5Ptk9bUpHLD8kbg_.base = 0;
NTI_d9cU6spIk5Ptk9bUpHLD8kbg_.flags = 3;
for (TM_jVF9a0kci0U9aAi0LWMoeYpg_5 = 0; TM_jVF9a0kci0U9aAi0LWMoeYpg_5 < 4; TM_jVF9a0kci0U9aAi0LWMoeYpg_5++) {
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[TM_jVF9a0kci0U9aAi0LWMoeYpg_5+3].kind = 1;
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[TM_jVF9a0kci0U9aAi0LWMoeYpg_5+3].offset = TM_jVF9a0kci0U9aAi0LWMoeYpg_5;
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[TM_jVF9a0kci0U9aAi0LWMoeYpg_5+3].name = TM_jVF9a0kci0U9aAi0LWMoeYpg_4[TM_jVF9a0kci0U9aAi0LWMoeYpg_5];
TM_jVF9a0kci0U9aAi0LWMoeYpg_3[TM_jVF9a0kci0U9aAi0LWMoeYpg_5] = &TM_jVF9a0kci0U9aAi0LWMoeYpg_0[TM_jVF9a0kci0U9aAi0LWMoeYpg_5+3];
}
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[7].len = 4; TM_jVF9a0kci0U9aAi0LWMoeYpg_0[7].kind = 2; TM_jVF9a0kci0U9aAi0LWMoeYpg_0[7].sons = &TM_jVF9a0kci0U9aAi0LWMoeYpg_3[0];
NTI_d9cU6spIk5Ptk9bUpHLD8kbg_.node = &TM_jVF9a0kci0U9aAi0LWMoeYpg_0[7];
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[2].kind = 1;
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[2].offset = offsetof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw, token_type);
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[2].typ = (&NTI_d9cU6spIk5Ptk9bUpHLD8kbg_);
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[2].name = "token_type";
TM_jVF9a0kci0U9aAi0LWMoeYpg_0[0].len = 2; TM_jVF9a0kci0U9aAi0LWMoeYpg_0[0].kind = 2; TM_jVF9a0kci0U9aAi0LWMoeYpg_0[0].sons = &TM_jVF9a0kci0U9aAi0LWMoeYpg_2[0];
NTI_q4PLD3QkwJJkBXqGWLsmCw_.node = &TM_jVF9a0kci0U9aAi0LWMoeYpg_0[0];
NTI_EGvzJYeQzBOu8VnhDxnsTg_.size = sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*);
NTI_EGvzJYeQzBOu8VnhDxnsTg_.kind = 22;
NTI_EGvzJYeQzBOu8VnhDxnsTg_.base = (&NTI_q4PLD3QkwJJkBXqGWLsmCw_);
NTI_EGvzJYeQzBOu8VnhDxnsTg_.flags = 2;
NTI_EGvzJYeQzBOu8VnhDxnsTg_.marker = Marker_tyRef_EGvzJYeQzBOu8VnhDxnsTg;
NTI_Ga09ahkQ9b222DUS9cyf8kbqg_.size = sizeof(tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*);
NTI_Ga09ahkQ9b222DUS9cyf8kbqg_.kind = 24;
NTI_Ga09ahkQ9b222DUS9cyf8kbqg_.base = (&NTI_EGvzJYeQzBOu8VnhDxnsTg_);
NTI_Ga09ahkQ9b222DUS9cyf8kbqg_.flags = 2;
NTI_Ga09ahkQ9b222DUS9cyf8kbqg_.marker = Marker_tySequence_Ga09ahkQ9b222DUS9cyf8kbqg;
}

