/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/s777675/.choosenim/toolchains/nim-0.18.0/lib -o '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/virtualmachine.o' '/Users/s777675/Documents/Nim/Turing Tarpit/Nim/src/nimcache/virtualmachine.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_y3L9bP9agLhaHxUzv09cBtsnQ tySequence_y3L9bP9agLhaHxUzv09cBtsnQ;
typedef struct tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg;
typedef struct tySequence_M9amFX5KaZeJ4Y3Xhzlxtew tySequence_M9amFX5KaZeJ4Y3Xhzlxtew;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g;
typedef struct tySequence_8sILwIxsvbEGHvqRfAqOuw tySequence_8sILwIxsvbEGHvqRfAqOuw;
typedef struct tyTuple_uUwBhYWaJVX4oTp0wobQJQ tyTuple_uUwBhYWaJVX4oTp0wobQJQ;
typedef struct tySequence_Ga09ahkQ9b222DUS9cyf8kbqg tySequence_Ga09ahkQ9b222DUS9cyf8kbqg;
typedef struct tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ tyTuple_3AUSAsdmFS3CNkloCsXPsQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg {
tySequence_M9amFX5KaZeJ4Y3Xhzlxtew* data;
NI counter;
};
struct tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg {
NimStringDesc* program;
tySequence_y3L9bP9agLhaHxUzv09cBtsnQ* data;
tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg registers;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
typedef NU8 tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg;
struct tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g {
tySequence_8sILwIxsvbEGHvqRfAqOuw* data;
NI counter;
};
struct tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* data;
tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg data_type;
tyObject_Table_WAyqrCgQAr5q2ts4Hy4n6g map;
};
struct tyTuple_uUwBhYWaJVX4oTp0wobQJQ {
NI Field0;
NimStringDesc* Field1;
tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* Field2;
};
typedef NU8 tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg;
struct tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw {
NimStringDesc* name;
tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg token_type;
};
typedef NIM_CHAR tyArray_0j8sSXZOeBGmu6W0H2n0Uw[10];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_3AUSAsdmFS3CNkloCsXPsQ {
NI Field0;
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Field1;
tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* Field2;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_y3L9bP9agLhaHxUzv09cBtsnQ {
  TGenericSeq Sup;
  tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data[SEQ_DECL_SIZE];
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_Ga09ahkQ9b222DUS9cyf8kbqg {
  TGenericSeq Sup;
  tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* data[SEQ_DECL_SIZE];
};
struct tySequence_M9amFX5KaZeJ4Y3Xhzlxtew {
  TGenericSeq Sup;
  tyTuple_uUwBhYWaJVX4oTp0wobQJQ data[SEQ_DECL_SIZE];
};
struct tySequence_8sILwIxsvbEGHvqRfAqOuw {
  TGenericSeq Sup;
  tyTuple_3AUSAsdmFS3CNkloCsXPsQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*, NewVirtualMachine_uYt4Wl0wVZx4yQjnla539cA)(NimStringDesc* program);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_y3L9bP9agLhaHxUzv09cBtsnQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_2lt378e8dPjnODvLPOQ2Rg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, initTable_nWX1GqiOanq8RVl9aiCGLRQ)(NI initialSize, tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__crSMYnCRe0jbOskT9a8KC2w)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg* t, NimStringDesc* key, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, NewType_1OrDvBSY7u52nJGIFy71LQ)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*, NewVirtualMachine_UtGlmyE8gl9comg4v9bh48eA)(NimStringDesc* program, tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* vm);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_P9cTCUF9bsFLyJycfCP3B2Fg)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
static N_INLINE(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_U9cLtFSiuKYIraJSICtOSuAvirtualmachine)(tySequence_y3L9bP9agLhaHxUzv09cBtsnQ** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(void, push_iRQeCvHAiTUOQiJiHS9b4rw)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__LB49bmI9btAcaHBpfQPNZnlQ)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* x, tySequence_Zj5xKXgsXnI4n4hPS6nACA* y);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, print_1ZVIadieGRNtczw5SHUtsA)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_ZSTRa9b146RfJCE4Q5aTd8A)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, print_7CDbz9bGshWK9b1JC8Y8cFmQ)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, input_1ZVIadieGRNtczw5SHUtsA_2)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, set_vrU9cS59aU8FM2hT9c9cFsS9aXA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, input_0ib9acUht4wiK9a8GHD8JyOQ)(void);
N_LIB_PRIVATE N_NIMCALL(void, push_9bkj57Zw1FsrkVtYamRXsDg)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, store_1ZVIadieGRNtczw5SHUtsA_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, name_GjhGrqzaqmtHWEG4AXjCLA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, load_1ZVIadieGRNtczw5SHUtsA_4)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**, X5BX5D__SWNlhuVMvclDmhmZXGZkTw)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, str_1ZVIadieGRNtczw5SHUtsA_5)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, character_1ZVIadieGRNtczw5SHUtsA_6)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, set_t6CEFOv6znBMha8waSyXsg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, NF data);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, character_BWGXL56BUNUogvZ1vpmA8Q)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
N_LIB_PRIVATE N_NIMCALL(void, add_1ZVIadieGRNtczw5SHUtsA_7)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, add_4lYSdUbPLhXZzAgY3UFcLg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, subtract_1ZVIadieGRNtczw5SHUtsA_8)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, subtract_4lYSdUbPLhXZzAgY3UFcLg_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, multiply_1ZVIadieGRNtczw5SHUtsA_9)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, multiply_4lYSdUbPLhXZzAgY3UFcLg_3)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, divide_1ZVIadieGRNtczw5SHUtsA_10)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, divide_4lYSdUbPLhXZzAgY3UFcLg_4)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, setMember_1ZVIadieGRNtczw5SHUtsA_11)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, load_Hk03t182DaLk1ms7Ml3iaw)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, setMember_9aMyF1zORtckEpFMAIgfJMA)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data);
N_LIB_PRIVATE N_NIMCALL(void, store_Hk03t182DaLk1ms7Ml3iaw_2)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, getMember_1ZVIadieGRNtczw5SHUtsA_12)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, getMember_v15KYyP7osL4iouqy0PNvg)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0, tySequence_Zj5xKXgsXnI4n4hPS6nACA* name);
N_LIB_PRIVATE N_NIMCALL(void, call_1ZVIadieGRNtczw5SHUtsA_13)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, str_GjhGrqzaqmtHWEG4AXjCLA_2)(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* this_0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, run_Hk03t182DaLk1ms7Ml3iaw_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, forloop_1ZVIadieGRNtczw5SHUtsA_14)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, call_Hk03t182DaLk1ms7Ml3iaw_4)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, whileloop_1ZVIadieGRNtczw5SHUtsA_15)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, run_1ZVIadieGRNtczw5SHUtsA_16)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*, Tokenize_ab9c9cD4QZzr08z9anmjNqcGQ)(NimStringDesc* program);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, whileloop_Hk03t182DaLk1ms7Ml3iaw_5)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, setMember_Hk03t182DaLk1ms7Ml3iaw_6)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, getMember_Hk03t182DaLk1ms7Ml3iaw_7)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, character_Hk03t182DaLk1ms7Ml3iaw_8)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, print_Hk03t182DaLk1ms7Ml3iaw_9)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, str_Hk03t182DaLk1ms7Ml3iaw_10)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, add_Hk03t182DaLk1ms7Ml3iaw_11)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, subtract_Hk03t182DaLk1ms7Ml3iaw_12)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, multiply_Hk03t182DaLk1ms7Ml3iaw_13)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, divide_Hk03t182DaLk1ms7Ml3iaw_14)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, forloop_Hk03t182DaLk1ms7Ml3iaw_15)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
N_LIB_PRIVATE N_NIMCALL(void, input_Hk03t182DaLk1ms7Ml3iaw_16)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0);
static N_INLINE(NI, rawGet_9c0dGoEZamLGRLGVD1iHrjQtables)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_3BJnT78t2TP8Y9bZlc420Yg)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_srGbBBjBtkfMqGy5N3yLrw)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg* t, tySequence_M9amFX5KaZeJ4Y3Xhzlxtew** data, NimStringDesc* key, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_edWbCIrjd0OZadECbuo6Gwtables)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg t, NimStringDesc* key, NI hc);
TNimType NTI_O9ahSrGWPxYaEFH55nFoWPg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_HTFzlhh8sr9a8r9c9bpxkl50w_;
TNimType NTI_y3L9bP9agLhaHxUzv09cBtsnQ_;
extern TNimType NTI_qzFgc5RlCN0Pzf9bJUk9cZMg_;
TNimType NTI_2lt378e8dPjnODvLPOQ2Rg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_M9amFX5KaZeJ4Y3Xhzlxtew_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
extern TNimType NTI_Ga09ahkQ9b222DUS9cyf8kbqg_;
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_3, "result", 6);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_5, " ", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_10, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST tyArray_0j8sSXZOeBGmu6W0H2n0Uw TM_8IRhL2MaKvJSUsLjmzeY9ag_13 = {48,
49,
50,
51,
52,
53,
54,
55,
56,
57}
;
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_14, "@", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_15, "\?", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_16, ",", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_17, ".", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_18, "~", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_19, "=", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_20, "$", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_21, "|", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_22, "!", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_23, "&", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_24, "+", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_25, "-", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_26, "*", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_27, "/", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_28, "^", 1);
STRING_LITERAL(TM_8IRhL2MaKvJSUsLjmzeY9ag_29, "%", 1);
static N_NIMCALL(void, Marker_tySequence_y3L9bP9agLhaHxUzv09cBtsnQ)(void* p, NI op) {
	tySequence_y3L9bP9agLhaHxUzv09cBtsnQ* a;
	NI T1_;
	a = (tySequence_y3L9bP9agLhaHxUzv09cBtsnQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_2lt378e8dPjnODvLPOQ2Rg)(void* p, NI op) {
	tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* a;
	a = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*)p;
	nimGCvisit((void*)(*a).program, op);
	nimGCvisit((void*)(*a).data, op);
	nimGCvisit((void*)(*a).registers.data, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*, NewVirtualMachine_uYt4Wl0wVZx4yQjnla539cA)(NimStringDesc* program) {
	tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* result;
	NimStringDesc* T1_;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T2_;
	nimfr_("NewVirtualMachine", "virtualmachine.nim");
	result = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*)0;
	nimln_(12, "virtualmachine.nim");
	result = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*) newObj((&NTI_2lt378e8dPjnODvLPOQ2Rg_), sizeof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg));
	nimln_(13, "virtualmachine.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).program; (*result).program = copyStringRC1(program);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(14, "virtualmachine.nim");
	if ((*result).data) { nimGCunrefNoCycle((*result).data); (*result).data = NIM_NIL; }
	(*result).data = (tySequence_y3L9bP9agLhaHxUzv09cBtsnQ*) newSeqRC1((&NTI_y3L9bP9agLhaHxUzv09cBtsnQ_), 0);
	nimln_(318, "tables.nim");
	initTable_nWX1GqiOanq8RVl9aiCGLRQ(((NI) 64), (&(*result).registers));
	nimln_(16, "virtualmachine.nim");
	T2_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T2_ = NewType_1OrDvBSY7u52nJGIFy71LQ();
	X5BX5Deq__crSMYnCRe0jbOskT9a8KC2w((&(*result).registers), ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_3), T2_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*, NewVirtualMachine_UtGlmyE8gl9comg4v9bh48eA)(NimStringDesc* program, tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* vm) {
	tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* result;
	NimStringDesc* T1_;
	nimfr_("NewVirtualMachine", "virtualmachine.nim");
	result = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*)0;
	nimln_(19, "virtualmachine.nim");
	result = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*) newObj((&NTI_2lt378e8dPjnODvLPOQ2Rg_), sizeof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg));
	nimln_(20, "virtualmachine.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).program; (*result).program = copyStringRC1(program);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(21, "virtualmachine.nim");
	genericSeqAssign((&(*result).data), (*vm).data, (&NTI_y3L9bP9agLhaHxUzv09cBtsnQ_));
	nimln_(22, "virtualmachine.nim");
	genericSeqAssign((&(*result).registers.data), (*vm).registers.data, (&NTI_M9amFX5KaZeJ4Y3Xhzlxtew_));
	(*result).registers.counter = (*vm).registers.counter;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_U9cLtFSiuKYIraJSICtOSuAvirtualmachine)(tySequence_y3L9bP9agLhaHxUzv09cBtsnQ** s) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	NI L;
	NI T1_;
	NI TM_8IRhL2MaKvJSUsLjmzeY9ag_4;
	nimfr_("pop", "system.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(2431, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_8IRhL2MaKvJSUsLjmzeY9ag_4 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_4);
	nimln_(2432, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = (*s)->data[L];
	nimln_(2433, "system.nim");
	(*s) = (tySequence_y3L9bP9agLhaHxUzv09cBtsnQ*) setLengthSeq(&((*s))->Sup, sizeof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*, pop_P9cTCUF9bsFLyJycfCP3B2Fg)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* result;
	nimfr_("pop", "virtualmachine.nim");
	result = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	nimln_(24, "virtualmachine.nim");
	result = pop_U9cLtFSiuKYIraJSICtOSuAvirtualmachine((&(*this_0).data));
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, push_iRQeCvHAiTUOQiJiHS9b4rw)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0, tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data) {
	nimfr_("push", "virtualmachine.nim");
	nimln_(26, "virtualmachine.nim");
	{
		tySequence_Zj5xKXgsXnI4n4hPS6nACA* T3_;
		NIM_BOOL T4_;
		NI T7_;
		nimln_(398, "system.nim");
		nimln_(26, "virtualmachine.nim");
		T3_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
		T3_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeq((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), 0);
		T4_ = (NIM_BOOL)0;
		T4_ = eqeq__LB49bmI9btAcaHBpfQPNZnlQ((*data).data, T3_);
		if (!!(T4_)) goto LA5_;
		nimln_(27, "virtualmachine.nim");
		(*this_0).data = (tySequence_y3L9bP9agLhaHxUzv09cBtsnQ*) incrSeqV2(&((*this_0).data)->Sup, sizeof(tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*));
		T7_ = (*this_0).data->Sup.len++;
		asgnRef((void**) (&(*this_0).data->data[T7_]), data);
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, print_1ZVIadieGRNtczw5SHUtsA)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data;
	nimfr_("print", "virtualmachine.nim");
	nimln_(30, "virtualmachine.nim");
	data = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(31, "virtualmachine.nim");
	print_7CDbz9bGshWK9b1JC8Y8cFmQ(data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, input_1ZVIadieGRNtczw5SHUtsA_2)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data;
	NimStringDesc* T1_;
	nimfr_("input", "virtualmachine.nim");
	nimln_(34, "virtualmachine.nim");
	data = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(35, "virtualmachine.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = input_0ib9acUht4wiK9a8GHD8JyOQ();
	set_vrU9cS59aU8FM2hT9c9cFsS9aXA(data, T1_);
	nimln_(36, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, store_1ZVIadieGRNtczw5SHUtsA_3)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	NimStringDesc* name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* value;
	nimfr_("store", "virtualmachine.nim");
	nimln_(39, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	name = name_GjhGrqzaqmtHWEG4AXjCLA(T1_);
	nimln_(40, "virtualmachine.nim");
	value = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(41, "virtualmachine.nim");
	X5BX5Deq__crSMYnCRe0jbOskT9a8KC2w((&(*this_0).registers), name, value);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, load_1ZVIadieGRNtczw5SHUtsA_4)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	NimStringDesc* name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ** T2_;
	nimfr_("load", "virtualmachine.nim");
	nimln_(44, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	name = name_GjhGrqzaqmtHWEG4AXjCLA(T1_);
	nimln_(45, "virtualmachine.nim");
	T2_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**)0;
	T2_ = X5BX5D__SWNlhuVMvclDmhmZXGZkTw((&(*this_0).registers), name);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, (*T2_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, str_1ZVIadieGRNtczw5SHUtsA_5)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data;
	NimStringDesc* T1_;
	nimfr_("str", "virtualmachine.nim");
	nimln_(48, "virtualmachine.nim");
	operand = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(49, "virtualmachine.nim");
	data = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(50, "virtualmachine.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = name_GjhGrqzaqmtHWEG4AXjCLA(operand);
	set_vrU9cS59aU8FM2hT9c9cFsS9aXA(data, T1_);
	nimln_(51, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, character_1ZVIadieGRNtczw5SHUtsA_6)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data;
	NIM_CHAR T1_;
	nimfr_("character", "virtualmachine.nim");
	nimln_(54, "virtualmachine.nim");
	operand = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(55, "virtualmachine.nim");
	data = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(56, "virtualmachine.nim");
	T1_ = (NIM_CHAR)0;
	T1_ = character_BWGXL56BUNUogvZ1vpmA8Q(operand);
	set_t6CEFOv6znBMha8waSyXsg(data, ((NF) (((NU8)(T1_)))));
	nimln_(57, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, add_1ZVIadieGRNtczw5SHUtsA_7)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand1;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand2;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	nimfr_("add", "virtualmachine.nim");
	nimln_(60, "virtualmachine.nim");
	operand1 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(61, "virtualmachine.nim");
	operand2 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(62, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = add_4lYSdUbPLhXZzAgY3UFcLg(operand1, operand2);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, subtract_1ZVIadieGRNtczw5SHUtsA_8)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand1;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand2;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	nimfr_("subtract", "virtualmachine.nim");
	nimln_(65, "virtualmachine.nim");
	operand1 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(66, "virtualmachine.nim");
	operand2 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(67, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = subtract_4lYSdUbPLhXZzAgY3UFcLg_2(operand1, operand2);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, multiply_1ZVIadieGRNtczw5SHUtsA_9)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand1;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand2;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	nimfr_("multiply", "virtualmachine.nim");
	nimln_(70, "virtualmachine.nim");
	operand1 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(71, "virtualmachine.nim");
	operand2 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(72, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = multiply_4lYSdUbPLhXZzAgY3UFcLg_3(operand1, operand2);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, divide_1ZVIadieGRNtczw5SHUtsA_10)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand1;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* operand2;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	nimfr_("divide", "virtualmachine.nim");
	nimln_(75, "virtualmachine.nim");
	operand1 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(76, "virtualmachine.nim");
	operand2 = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(77, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = divide_4lYSdUbPLhXZzAgY3UFcLg_4(operand1, operand2);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setMember_1ZVIadieGRNtczw5SHUtsA_11)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* obj_name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* member_name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* value;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* obj;
	nimfr_("setMember", "virtualmachine.nim");
	nimln_(80, "virtualmachine.nim");
	obj_name = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(81, "virtualmachine.nim");
	member_name = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(82, "virtualmachine.nim");
	value = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(85, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, obj_name);
	nimln_(86, "virtualmachine.nim");
	load_Hk03t182DaLk1ms7Ml3iaw(this_0);
	nimln_(87, "virtualmachine.nim");
	obj = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(88, "virtualmachine.nim");
	setMember_9aMyF1zORtckEpFMAIgfJMA(obj, (*member_name).data, value);
	nimln_(91, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, obj);
	nimln_(92, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, obj_name);
	nimln_(93, "virtualmachine.nim");
	store_Hk03t182DaLk1ms7Ml3iaw_2(this_0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getMember_1ZVIadieGRNtczw5SHUtsA_12)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* obj_name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* member_name;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* obj;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	nimfr_("getMember", "virtualmachine.nim");
	nimln_(96, "virtualmachine.nim");
	obj_name = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(97, "virtualmachine.nim");
	member_name = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(100, "virtualmachine.nim");
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, obj_name);
	nimln_(101, "virtualmachine.nim");
	load_Hk03t182DaLk1ms7Ml3iaw(this_0);
	nimln_(102, "virtualmachine.nim");
	obj = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(103, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = getMember_v15KYyP7osL4iouqy0PNvg(obj, (*member_name).data);
	push_9bkj57Zw1FsrkVtYamRXsDg(this_0, T1_);
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, call_1ZVIadieGRNtczw5SHUtsA_13)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	NimStringDesc* program;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T1_;
	tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* subroutine;
	NimStringDesc* T2_;
	nimfr_("call", "virtualmachine.nim");
	nimln_(108, "virtualmachine.nim");
	T1_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
	T1_ = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	program = str_GjhGrqzaqmtHWEG4AXjCLA_2(T1_);
	nimln_(109, "virtualmachine.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = rawNewString(program->Sup.len + 2);
appendString(T2_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
appendString(T2_, program);
appendString(T2_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
	subroutine = NewVirtualMachine_UtGlmyE8gl9comg4v9bh48eA(T2_, this_0);
	nimln_(110, "virtualmachine.nim");
	run_Hk03t182DaLk1ms7Ml3iaw_3(subroutine);
	nimln_(111, "virtualmachine.nim");
	genericSeqAssign((&(*this_0).data), (*subroutine).data, (&NTI_y3L9bP9agLhaHxUzv09cBtsnQ_));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, forloop_1ZVIadieGRNtczw5SHUtsA_14)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* n;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* function;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* data;
	nimfr_("forloop", "virtualmachine.nim");
	nimln_(114, "virtualmachine.nim");
	n = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(115, "virtualmachine.nim");
	function = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(116, "virtualmachine.nim");
	data = NewType_1OrDvBSY7u52nJGIFy71LQ();
	nimln_(117, "virtualmachine.nim");
	{
		if (!((*n).data_type == ((tyEnum_DataTypes_WCChZCx9aK9bdnLmmheMmbJg) 1))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(118, "virtualmachine.nim");
			if ((NU)(((NI) 0)) >= (NU)((*n).data->Sup.len)) raiseIndexError();
			colontmp_ = ((NI) ((*n).data->data[((NI) 0)]));
			nimln_(2032, "system.nim");
			res = ((NI) 0);
			{
				nimln_(2033, "system.nim");
				while (1) {
					NI TM_8IRhL2MaKvJSUsLjmzeY9ag_6;
					if (!(res <= colontmp_)) goto LA7;
					nimln_(2034, "system.nim");
					i = res;
					nimln_(119, "virtualmachine.nim");
					set_t6CEFOv6znBMha8waSyXsg(data, ((NF) (i)));
					nimln_(120, "virtualmachine.nim");
					push_9bkj57Zw1FsrkVtYamRXsDg(this_0, data);
					nimln_(121, "virtualmachine.nim");
					push_9bkj57Zw1FsrkVtYamRXsDg(this_0, function);
					nimln_(122, "virtualmachine.nim");
					call_Hk03t182DaLk1ms7Ml3iaw_4(this_0);
					nimln_(2035, "system.nim");
					TM_8IRhL2MaKvJSUsLjmzeY9ag_6 = addInt(res, ((NI) 1));
					res = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_6);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, whileloop_1ZVIadieGRNtczw5SHUtsA_15)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* condition;
	tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* function;
	NimStringDesc* program;
	tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* subroutine;
	nimfr_("whileloop", "virtualmachine.nim");
	nimln_(126, "virtualmachine.nim");
	condition = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(127, "virtualmachine.nim");
	function = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
	nimln_(129, "virtualmachine.nim");
	program = str_GjhGrqzaqmtHWEG4AXjCLA_2(condition);
	subroutine = (tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*)0;
	{
		nimln_(134, "virtualmachine.nim");
		while (1) {
			NimStringDesc* T3_;
			tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* return_value;
			nimln_(135, "virtualmachine.nim");
			T3_ = (NimStringDesc*)0;
			T3_ = rawNewString(program->Sup.len + 2);
appendString(T3_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
appendString(T3_, program);
appendString(T3_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
			subroutine = NewVirtualMachine_UtGlmyE8gl9comg4v9bh48eA(T3_, this_0);
			nimln_(136, "virtualmachine.nim");
			run_Hk03t182DaLk1ms7Ml3iaw_3(subroutine);
			{
				NimStringDesc* key;
				tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg colontmp_;
				key = (NimStringDesc*)0;
				memset((void*)(&colontmp_), 0, sizeof(colontmp_));
				nimln_(138, "virtualmachine.nim");
				colontmp_.data = (*subroutine).registers.data;
				colontmp_.counter = (*subroutine).registers.counter;
				{
					NI h;
					NI colontmp__2;
					NI T6_;
					NI res;
					h = (NI)0;
					colontmp__2 = (NI)0;
					nimln_(255, "tables.nim");
					T6_ = (colontmp_.data ? (colontmp_.data->Sup.len-1) : -1);
					colontmp__2 = T6_;
					nimln_(2045, "system.nim");
					res = ((NI) 0);
					{
						nimln_(2046, "system.nim");
						while (1) {
							NI TM_8IRhL2MaKvJSUsLjmzeY9ag_7;
							if (!(res <= colontmp__2)) goto LA8;
							nimln_(2047, "system.nim");
							h = res;
							nimln_(256, "tables.nim");
							{
								NIM_BOOL T11_;
								tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ** T14_;
								if ((NU)(h) >= (NU)(colontmp_.data->Sup.len)) raiseIndexError();
								T11_ = (NIM_BOOL)0;
								T11_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(colontmp_.data->data[h].Field0);
								if (!T11_) goto LA12_;
								if ((NU)(h) >= (NU)(colontmp_.data->Sup.len)) raiseIndexError();
								key = colontmp_.data->data[h].Field1;
								nimln_(139, "virtualmachine.nim");
								T14_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**)0;
								T14_ = X5BX5D__SWNlhuVMvclDmhmZXGZkTw((&(*subroutine).registers), key);
								X5BX5Deq__crSMYnCRe0jbOskT9a8KC2w((&(*this_0).registers), key, (*T14_));
							}
							LA12_: ;
							nimln_(2048, "system.nim");
							TM_8IRhL2MaKvJSUsLjmzeY9ag_7 = addInt(res, ((NI) 1));
							res = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_7);
						} LA8: ;
					}
				}
			}
			nimln_(141, "virtualmachine.nim");
			return_value = NewType_1OrDvBSY7u52nJGIFy71LQ();
			nimln_(142, "virtualmachine.nim");
			{
				NI T17_;
				T17_ = ((*subroutine).data ? (*subroutine).data->Sup.len : 0);
				if (!(((NI) 0) < T17_)) goto LA18_;
				nimln_(143, "virtualmachine.nim");
				return_value = pop_ZSTRa9b146RfJCE4Q5aTd8A(subroutine);
			}
			LA18_: ;
			nimln_(145, "virtualmachine.nim");
			{
				NimStringDesc* T24_;
				NimStringDesc* T25_;
				nimln_(398, "system.nim");
				nimln_(145, "virtualmachine.nim");
				if ((NU)(((NI) 0)) >= (NU)((*return_value).data->Sup.len)) raiseIndexError();
				if (!!((((NI) ((*return_value).data->data[((NI) 0)])) == ((NI) 0)))) goto LA22_;
				nimln_(146, "virtualmachine.nim");
				T24_ = (NimStringDesc*)0;
				T25_ = (NimStringDesc*)0;
				T25_ = str_GjhGrqzaqmtHWEG4AXjCLA_2(function);
				T24_ = rawNewString(T25_->Sup.len + 2);
appendString(T24_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
appendString(T24_, T25_);
appendString(T24_, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_5));
				subroutine = NewVirtualMachine_UtGlmyE8gl9comg4v9bh48eA(T24_, this_0);
				nimln_(147, "virtualmachine.nim");
				run_Hk03t182DaLk1ms7Ml3iaw_3(subroutine);
				{
					NimStringDesc* key_2;
					tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg colontmp__3;
					key_2 = (NimStringDesc*)0;
					memset((void*)(&colontmp__3), 0, sizeof(colontmp__3));
					nimln_(149, "virtualmachine.nim");
					colontmp__3.data = (*subroutine).registers.data;
					colontmp__3.counter = (*subroutine).registers.counter;
					{
						NI h_2;
						NI colontmp__4;
						NI T28_;
						NI res_2;
						h_2 = (NI)0;
						colontmp__4 = (NI)0;
						nimln_(255, "tables.nim");
						T28_ = (colontmp__3.data ? (colontmp__3.data->Sup.len-1) : -1);
						colontmp__4 = T28_;
						nimln_(2045, "system.nim");
						res_2 = ((NI) 0);
						{
							nimln_(2046, "system.nim");
							while (1) {
								NI TM_8IRhL2MaKvJSUsLjmzeY9ag_8;
								if (!(res_2 <= colontmp__4)) goto LA30;
								nimln_(2047, "system.nim");
								h_2 = res_2;
								nimln_(256, "tables.nim");
								{
									NIM_BOOL T33_;
									tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ** T36_;
									if ((NU)(h_2) >= (NU)(colontmp__3.data->Sup.len)) raiseIndexError();
									T33_ = (NIM_BOOL)0;
									T33_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(colontmp__3.data->data[h_2].Field0);
									if (!T33_) goto LA34_;
									if ((NU)(h_2) >= (NU)(colontmp__3.data->Sup.len)) raiseIndexError();
									key_2 = colontmp__3.data->data[h_2].Field1;
									nimln_(150, "virtualmachine.nim");
									T36_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ**)0;
									T36_ = X5BX5D__SWNlhuVMvclDmhmZXGZkTw((&(*subroutine).registers), key_2);
									X5BX5Deq__crSMYnCRe0jbOskT9a8KC2w((&(*this_0).registers), key_2, (*T36_));
								}
								LA34_: ;
								nimln_(2048, "system.nim");
								TM_8IRhL2MaKvJSUsLjmzeY9ag_8 = addInt(res_2, ((NI) 1));
								res_2 = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_8);
							} LA30: ;
						}
					}
				}
				nimln_(152, "virtualmachine.nim");
				genericSeqAssign((&(*this_0).data), (*subroutine).data, (&NTI_y3L9bP9agLhaHxUzv09cBtsnQ_));
			}
			goto LA20_;
			LA22_: ;
			{
				nimln_(154, "virtualmachine.nim");
				goto LA1;
			}
			LA20_: ;
		}
	} LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NIM_CHAR i;
		NI i_2;
		i = (NIM_CHAR)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_8IRhL2MaKvJSUsLjmzeY9ag_11;
				NI TM_8IRhL2MaKvJSUsLjmzeY9ag_12;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!((NU8)(i) == (NU8)(item))) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_8IRhL2MaKvJSUsLjmzeY9ag_11 = addInt(result, ((NI) 1));
				result = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_11);
				nimln_(2188, "system.nim");
				TM_8IRhL2MaKvJSUsLjmzeY9ag_12 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_12);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b3HPX1XboPhUmnxkTjazFQstrutils(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, run_1ZVIadieGRNtczw5SHUtsA_16)(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg* this_0) {
	tySequence_Ga09ahkQ9b222DUS9cyf8kbqg* tokens;
	tySequence_Ga09ahkQ9b222DUS9cyf8kbqg* newtokens;
	nimfr_("run", "virtualmachine.nim");
	nimln_(158, "virtualmachine.nim");
	tokens = Tokenize_ab9c9cD4QZzr08z9anmjNqcGQ((*this_0).program);
	nimln_(159, "virtualmachine.nim");
	newtokens = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) newSeq((&NTI_Ga09ahkQ9b222DUS9cyf8kbqg_), 0);
	{
		tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* token;
		NI i;
		NI L;
		NI T2_;
		token = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (tokens ? tokens->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_8IRhL2MaKvJSUsLjmzeY9ag_9;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(tokens->Sup.len)) raiseIndexError();
				token = tokens->data[i];
				nimln_(161, "virtualmachine.nim");
				{
					NIM_BOOL T7_;
					NI T11_;
					T7_ = (NIM_BOOL)0;
					T7_ = ((*token).token_type == ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 2));
					if (!(T7_)) goto LA8_;
					T7_ = (((*token).name) && ((*token).name)->Sup.len == 0);
					LA8_: ;
					if (!!(T7_)) goto LA9_;
					nimln_(162, "virtualmachine.nim");
					newtokens = (tySequence_Ga09ahkQ9b222DUS9cyf8kbqg*) incrSeqV2(&(newtokens)->Sup, sizeof(tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*));
					T11_ = newtokens->Sup.len++;
					asgnRefNoCycle((void**) (&newtokens->data[T11_]), token);
				}
				LA9_: ;
				nimln_(3809, "system.nim");
				TM_8IRhL2MaKvJSUsLjmzeY9ag_9 = addInt(i, ((NI) 1));
				i = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_9);
				nimln_(3810, "system.nim");
				{
					NI T14_;
					T14_ = (tokens ? tokens->Sup.len : 0);
					if (!!((T14_ == L))) goto LA15_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_10));
				}
				LA15_: ;
			} LA4: ;
		}
	}
	nimln_(164, "virtualmachine.nim");
	genericSeqAssign((&tokens), newtokens, (&NTI_Ga09ahkQ9b222DUS9cyf8kbqg_));
	{
		tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw* token_2;
		NI i_2;
		NI L_2;
		NI T18_;
		token_2 = (tyObject_TokencolonObjectType__q4PLD3QkwJJkBXqGWLsmCw*)0;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T18_ = (tokens ? tokens->Sup.len : 0);
		L_2 = T18_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_8IRhL2MaKvJSUsLjmzeY9ag_30;
				if (!(i_2 < L_2)) goto LA20;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(tokens->Sup.len)) raiseIndexError();
				token_2 = tokens->data[i_2];
				nimln_(175, "virtualmachine.nim");
				switch ((*token_2).token_type) {
				case ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 2):
				{
					tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* newtype;
					nimln_(177, "virtualmachine.nim");
					newtype = NewType_1OrDvBSY7u52nJGIFy71LQ();
					nimln_(178, "virtualmachine.nim");
					set_vrU9cS59aU8FM2hT9c9cFsS9aXA(newtype, (*token_2).name);
					nimln_(179, "virtualmachine.nim");
					push_9bkj57Zw1FsrkVtYamRXsDg(this_0, newtype);
				}
				break;
				case ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 1):
				{
					nimln_(182, "virtualmachine.nim");
					{
						NIM_BOOL T25_;
						tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* newtype_2;
						NF T28_;
						if ((NU)(((NI) 0)) > (NU)((*token_2).name->Sup.len)) raiseIndexError();
						T25_ = (NIM_BOOL)0;
						T25_ = contains_I9cy9aN2znlBRynMcXN4pBGgstrutils(TM_8IRhL2MaKvJSUsLjmzeY9ag_13, 10, (*token_2).name->data[((NI) 0)]);
						if (!T25_) goto LA26_;
						nimln_(183, "virtualmachine.nim");
						newtype_2 = NewType_1OrDvBSY7u52nJGIFy71LQ();
						nimln_(184, "virtualmachine.nim");
						T28_ = (NF)0;
						T28_ = nsuParseFloat((*token_2).name);
						set_t6CEFOv6znBMha8waSyXsg(newtype_2, T28_);
						nimln_(185, "virtualmachine.nim");
						push_9bkj57Zw1FsrkVtYamRXsDg(this_0, newtype_2);
					}
					goto LA23_;
					LA26_: ;
					{
						tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* newtype_3;
						nimln_(188, "virtualmachine.nim");
						newtype_3 = NewType_1OrDvBSY7u52nJGIFy71LQ();
						nimln_(189, "virtualmachine.nim");
						set_vrU9cS59aU8FM2hT9c9cFsS9aXA(newtype_3, (*token_2).name);
						nimln_(190, "virtualmachine.nim");
						push_9bkj57Zw1FsrkVtYamRXsDg(this_0, newtype_3);
					}
					LA23_: ;
				}
				break;
				case ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 0):
				{
					tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* newtype_4;
					nimln_(193, "virtualmachine.nim");
					newtype_4 = NewType_1OrDvBSY7u52nJGIFy71LQ();
					nimln_(194, "virtualmachine.nim");
					set_vrU9cS59aU8FM2hT9c9cFsS9aXA(newtype_4, (*token_2).name);
					nimln_(195, "virtualmachine.nim");
					push_9bkj57Zw1FsrkVtYamRXsDg(this_0, newtype_4);
				}
				break;
				case ((tyEnum_TokenType_d9cU6spIk5Ptk9bUpHLD8kbg) 3):
				{
					nimln_(198, "virtualmachine.nim");
					switch (hashString((*token_2).name) & 15) {
					case 0: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_20))) goto LA38_;
break;
					case 1: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_27))) goto LA45_;
break;
					case 3: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_19))) goto LA37_;
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_21))) goto LA39_;
break;
					case 4: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_29))) goto LA47_;
break;
					case 5: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_16))) goto LA34_;
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_26))) goto LA44_;
break;
					case 7: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_24))) goto LA42_;
break;
					case 8: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_15))) goto LA33_;
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_18))) goto LA36_;
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_25))) goto LA43_;
break;
					case 10: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_28))) goto LA46_;
break;
					case 11: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_23))) goto LA41_;
break;
					case 12: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_17))) goto LA35_;
break;
					case 13: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_14))) goto LA32_;
break;
					case 15: 
if (eqStrings((*token_2).name, ((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_22))) goto LA40_;
break;
					}
					goto LA48_;
					LA32_: ;
					{
						tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ* T51_;
						nimln_(199, "virtualmachine.nim");
						T51_ = (tyObject_TypecolonObjectType__mf33P9ac6h0JtdyXNBo6iKQ*)0;
						T51_ = pop_ZSTRa9b146RfJCE4Q5aTd8A(this_0);
						T51_;
					}
					goto LA49_;
					LA33_: ;
					{
						nimln_(200, "virtualmachine.nim");
						whileloop_Hk03t182DaLk1ms7Ml3iaw_5(this_0);
					}
					goto LA49_;
					LA34_: ;
					{
						nimln_(201, "virtualmachine.nim");
						setMember_Hk03t182DaLk1ms7Ml3iaw_6(this_0);
					}
					goto LA49_;
					LA35_: ;
					{
						nimln_(202, "virtualmachine.nim");
						getMember_Hk03t182DaLk1ms7Ml3iaw_7(this_0);
					}
					goto LA49_;
					LA36_: ;
					{
						nimln_(203, "virtualmachine.nim");
						character_Hk03t182DaLk1ms7Ml3iaw_8(this_0);
					}
					goto LA49_;
					LA37_: ;
					{
						nimln_(204, "virtualmachine.nim");
						store_Hk03t182DaLk1ms7Ml3iaw_2(this_0);
					}
					goto LA49_;
					LA38_: ;
					{
						nimln_(205, "virtualmachine.nim");
						load_Hk03t182DaLk1ms7Ml3iaw(this_0);
					}
					goto LA49_;
					LA39_: ;
					{
						nimln_(206, "virtualmachine.nim");
						print_Hk03t182DaLk1ms7Ml3iaw_9(this_0);
					}
					goto LA49_;
					LA40_: ;
					{
						nimln_(207, "virtualmachine.nim");
						call_Hk03t182DaLk1ms7Ml3iaw_4(this_0);
					}
					goto LA49_;
					LA41_: ;
					{
						nimln_(208, "virtualmachine.nim");
						str_Hk03t182DaLk1ms7Ml3iaw_10(this_0);
					}
					goto LA49_;
					LA42_: ;
					{
						nimln_(209, "virtualmachine.nim");
						add_Hk03t182DaLk1ms7Ml3iaw_11(this_0);
					}
					goto LA49_;
					LA43_: ;
					{
						nimln_(210, "virtualmachine.nim");
						subtract_Hk03t182DaLk1ms7Ml3iaw_12(this_0);
					}
					goto LA49_;
					LA44_: ;
					{
						nimln_(211, "virtualmachine.nim");
						multiply_Hk03t182DaLk1ms7Ml3iaw_13(this_0);
					}
					goto LA49_;
					LA45_: ;
					{
						nimln_(212, "virtualmachine.nim");
						divide_Hk03t182DaLk1ms7Ml3iaw_14(this_0);
					}
					goto LA49_;
					LA46_: ;
					{
						nimln_(213, "virtualmachine.nim");
						forloop_Hk03t182DaLk1ms7Ml3iaw_15(this_0);
					}
					goto LA49_;
					LA47_: ;
					{
						nimln_(214, "virtualmachine.nim");
						input_Hk03t182DaLk1ms7Ml3iaw_16(this_0);
					}
					goto LA49_;
					LA48_: ;
					{
					}
					LA49_: ;
				}
				break;
				default:
				{
				}
				break;
				}
				nimln_(3809, "system.nim");
				TM_8IRhL2MaKvJSUsLjmzeY9ag_30 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_30);
				nimln_(3810, "system.nim");
				{
					NI T71_;
					T71_ = (tokens ? tokens->Sup.len : 0);
					if (!!((T71_ == L_2))) goto LA72_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_8IRhL2MaKvJSUsLjmzeY9ag_10));
				}
				LA72_: ;
			} LA20: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_8IRhL2MaKvJSUsLjmzeY9ag_31;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_8IRhL2MaKvJSUsLjmzeY9ag_31 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_31) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_9c0dGoEZamLGRLGVD1iHrjQtables)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_8IRhL2MaKvJSUsLjmzeY9ag_32;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_8IRhL2MaKvJSUsLjmzeY9ag_32 = subInt(((NI) -1), h);
	result = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_32);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_edWbCIrjd0OZadECbuo6Gwtables)(tyObject_Table_qzFgc5RlCN0Pzf9bJUk9cZMg t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_8IRhL2MaKvJSUsLjmzeY9ag_33;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_8IRhL2MaKvJSUsLjmzeY9ag_33 = subInt(((NI) -1), h);
	result = (NI)(TM_8IRhL2MaKvJSUsLjmzeY9ag_33);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_virtualmachineInit000)(void) {
	nimfr_("virtualmachine", "virtualmachine.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_virtualmachineDatInit000)(void) {
static TNimNode* TM_8IRhL2MaKvJSUsLjmzeY9ag_2[3];
static TNimNode TM_8IRhL2MaKvJSUsLjmzeY9ag_0[4];
NTI_O9ahSrGWPxYaEFH55nFoWPg_.size = sizeof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg);
NTI_O9ahSrGWPxYaEFH55nFoWPg_.kind = 18;
NTI_O9ahSrGWPxYaEFH55nFoWPg_.base = 0;
NTI_O9ahSrGWPxYaEFH55nFoWPg_.flags = 2;
TM_8IRhL2MaKvJSUsLjmzeY9ag_2[0] = &TM_8IRhL2MaKvJSUsLjmzeY9ag_0[1];
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[1].kind = 1;
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[1].offset = offsetof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg, program);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[1].name = "program";
TM_8IRhL2MaKvJSUsLjmzeY9ag_2[1] = &TM_8IRhL2MaKvJSUsLjmzeY9ag_0[2];
NTI_y3L9bP9agLhaHxUzv09cBtsnQ_.size = sizeof(tySequence_y3L9bP9agLhaHxUzv09cBtsnQ*);
NTI_y3L9bP9agLhaHxUzv09cBtsnQ_.kind = 24;
NTI_y3L9bP9agLhaHxUzv09cBtsnQ_.base = (&NTI_HTFzlhh8sr9a8r9c9bpxkl50w_);
NTI_y3L9bP9agLhaHxUzv09cBtsnQ_.flags = 2;
NTI_y3L9bP9agLhaHxUzv09cBtsnQ_.marker = Marker_tySequence_y3L9bP9agLhaHxUzv09cBtsnQ;
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[2].kind = 1;
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[2].offset = offsetof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg, data);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[2].typ = (&NTI_y3L9bP9agLhaHxUzv09cBtsnQ_);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[2].name = "data";
TM_8IRhL2MaKvJSUsLjmzeY9ag_2[2] = &TM_8IRhL2MaKvJSUsLjmzeY9ag_0[3];
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[3].kind = 1;
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[3].offset = offsetof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg, registers);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[3].typ = (&NTI_qzFgc5RlCN0Pzf9bJUk9cZMg_);
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[3].name = "registers";
TM_8IRhL2MaKvJSUsLjmzeY9ag_0[0].len = 3; TM_8IRhL2MaKvJSUsLjmzeY9ag_0[0].kind = 2; TM_8IRhL2MaKvJSUsLjmzeY9ag_0[0].sons = &TM_8IRhL2MaKvJSUsLjmzeY9ag_2[0];
NTI_O9ahSrGWPxYaEFH55nFoWPg_.node = &TM_8IRhL2MaKvJSUsLjmzeY9ag_0[0];
NTI_2lt378e8dPjnODvLPOQ2Rg_.size = sizeof(tyObject_VirtualMachinecolonObjectType__O9ahSrGWPxYaEFH55nFoWPg*);
NTI_2lt378e8dPjnODvLPOQ2Rg_.kind = 22;
NTI_2lt378e8dPjnODvLPOQ2Rg_.base = (&NTI_O9ahSrGWPxYaEFH55nFoWPg_);
NTI_2lt378e8dPjnODvLPOQ2Rg_.flags = 2;
NTI_2lt378e8dPjnODvLPOQ2Rg_.marker = Marker_tyRef_2lt378e8dPjnODvLPOQ2Rg;
}

